// File generated from our OpenAPI spec by Stainless.

package dev.cjav.spotted.models.playlists

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import dev.cjav.spotted.core.jsonMapper
import dev.cjav.spotted.models.AlbumRestrictionObject
import dev.cjav.spotted.models.ExternalIdObject
import dev.cjav.spotted.models.ExternalUrlObject
import dev.cjav.spotted.models.FollowersObject
import dev.cjav.spotted.models.ImageObject
import dev.cjav.spotted.models.LinkedTrackObject
import dev.cjav.spotted.models.PlaylistTrackObject
import dev.cjav.spotted.models.PlaylistUserObject
import dev.cjav.spotted.models.SimplifiedArtistObject
import dev.cjav.spotted.models.TrackObject
import dev.cjav.spotted.models.TrackRestrictionObject
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PlaylistRetrieveResponseTest {

    @Test
    fun create() {
        val playlistRetrieveResponse =
            PlaylistRetrieveResponse.builder()
                .id("id")
                .componentsSchemasPropertiesIsPublic(true)
                .collaborative(true)
                .description("description")
                .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                .followers(FollowersObject.builder().href("href").total(0L).build())
                .href("href")
                .addImage(
                    ImageObject.builder()
                        .height(300L)
                        .url("https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n")
                        .width(300L)
                        .build()
                )
                .name("name")
                .owner(
                    PlaylistRetrieveResponse.Owner.builder()
                        .id("id")
                        .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                        .href("href")
                        .type(PlaylistUserObject.Type.USER)
                        .uri("uri")
                        .displayName("display_name")
                        .build()
                )
                .snapshotId("snapshot_id")
                .tracks(
                    PlaylistRetrieveResponse.Tracks.builder()
                        .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                        .limit(20L)
                        .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .offset(0L)
                        .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .total(4L)
                        .addItem(
                            PlaylistTrackObject.builder()
                                .addedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .addedBy(
                                    PlaylistUserObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .type(PlaylistUserObject.Type.USER)
                                        .uri("uri")
                                        .build()
                                )
                                .isLocal(true)
                                .track(
                                    TrackObject.builder()
                                        .id("id")
                                        .album(
                                            TrackObject.Album.builder()
                                                .id("2up3OPMp9Tb4dAKM2erWXQ")
                                                .albumType(TrackObject.Album.AlbumType.COMPILATION)
                                                .addArtist(
                                                    SimplifiedArtistObject.builder()
                                                        .id("id")
                                                        .externalUrls(
                                                            ExternalUrlObject.builder()
                                                                .spotify("spotify")
                                                                .build()
                                                        )
                                                        .href("href")
                                                        .name("name")
                                                        .type(SimplifiedArtistObject.Type.ARTIST)
                                                        .uri("uri")
                                                        .build()
                                                )
                                                .availableMarkets(listOf("CA", "BR", "IT"))
                                                .externalUrls(
                                                    ExternalUrlObject.builder()
                                                        .spotify("spotify")
                                                        .build()
                                                )
                                                .href("href")
                                                .addImage(
                                                    ImageObject.builder()
                                                        .height(300L)
                                                        .url(
                                                            "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                                        )
                                                        .width(300L)
                                                        .build()
                                                )
                                                .name("name")
                                                .releaseDate("1981-12")
                                                .releaseDatePrecision(
                                                    TrackObject.Album.ReleaseDatePrecision.YEAR
                                                )
                                                .totalTracks(9L)
                                                .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                                                .restrictions(
                                                    AlbumRestrictionObject.builder()
                                                        .reason(
                                                            AlbumRestrictionObject.Reason.MARKET
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .addArtist(
                                            SimplifiedArtistObject.builder()
                                                .id("id")
                                                .externalUrls(
                                                    ExternalUrlObject.builder()
                                                        .spotify("spotify")
                                                        .build()
                                                )
                                                .href("href")
                                                .name("name")
                                                .type(SimplifiedArtistObject.Type.ARTIST)
                                                .uri("uri")
                                                .build()
                                        )
                                        .addAvailableMarket("string")
                                        .discNumber(0L)
                                        .durationMs(0L)
                                        .explicit(true)
                                        .externalIds(
                                            ExternalIdObject.builder()
                                                .ean("ean")
                                                .isrc("isrc")
                                                .upc("upc")
                                                .build()
                                        )
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .isLocal(true)
                                        .isPlayable(true)
                                        .linkedFrom(
                                            LinkedTrackObject.builder()
                                                .id("id")
                                                .externalUrls(
                                                    ExternalUrlObject.builder()
                                                        .spotify("spotify")
                                                        .build()
                                                )
                                                .href("href")
                                                .type("type")
                                                .uri("uri")
                                                .build()
                                        )
                                        .name("name")
                                        .popularity(0L)
                                        .previewUrl("preview_url")
                                        .restrictions(
                                            TrackRestrictionObject.builder()
                                                .reason("reason")
                                                .build()
                                        )
                                        .trackNumber(0L)
                                        .type(TrackObject.Type.TRACK)
                                        .uri("uri")
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .type("type")
                .uri("uri")
                .build()

        assertThat(playlistRetrieveResponse.id()).isEqualTo("id")
        assertThat(playlistRetrieveResponse.componentsSchemasPropertiesIsPublic()).isEqualTo(true)
        assertThat(playlistRetrieveResponse.collaborative()).isEqualTo(true)
        assertThat(playlistRetrieveResponse.description()).isEqualTo("description")
        assertThat(playlistRetrieveResponse.externalUrls())
            .isEqualTo(ExternalUrlObject.builder().spotify("spotify").build())
        assertThat(playlistRetrieveResponse.followers())
            .isEqualTo(FollowersObject.builder().href("href").total(0L).build())
        assertThat(playlistRetrieveResponse.href()).isEqualTo("href")
        assertThat(playlistRetrieveResponse.images())
            .containsExactly(
                ImageObject.builder()
                    .height(300L)
                    .url("https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n")
                    .width(300L)
                    .build()
            )
        assertThat(playlistRetrieveResponse.name()).isEqualTo("name")
        assertThat(playlistRetrieveResponse.owner())
            .isEqualTo(
                PlaylistRetrieveResponse.Owner.builder()
                    .id("id")
                    .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                    .href("href")
                    .type(PlaylistUserObject.Type.USER)
                    .uri("uri")
                    .displayName("display_name")
                    .build()
            )
        assertThat(playlistRetrieveResponse.snapshotId()).isEqualTo("snapshot_id")
        assertThat(playlistRetrieveResponse.tracks())
            .isEqualTo(
                PlaylistRetrieveResponse.Tracks.builder()
                    .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                    .limit(20L)
                    .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                    .offset(0L)
                    .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                    .total(4L)
                    .addItem(
                        PlaylistTrackObject.builder()
                            .addedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .addedBy(
                                PlaylistUserObject.builder()
                                    .id("id")
                                    .externalUrls(
                                        ExternalUrlObject.builder().spotify("spotify").build()
                                    )
                                    .href("href")
                                    .type(PlaylistUserObject.Type.USER)
                                    .uri("uri")
                                    .build()
                            )
                            .isLocal(true)
                            .track(
                                TrackObject.builder()
                                    .id("id")
                                    .album(
                                        TrackObject.Album.builder()
                                            .id("2up3OPMp9Tb4dAKM2erWXQ")
                                            .albumType(TrackObject.Album.AlbumType.COMPILATION)
                                            .addArtist(
                                                SimplifiedArtistObject.builder()
                                                    .id("id")
                                                    .externalUrls(
                                                        ExternalUrlObject.builder()
                                                            .spotify("spotify")
                                                            .build()
                                                    )
                                                    .href("href")
                                                    .name("name")
                                                    .type(SimplifiedArtistObject.Type.ARTIST)
                                                    .uri("uri")
                                                    .build()
                                            )
                                            .availableMarkets(listOf("CA", "BR", "IT"))
                                            .externalUrls(
                                                ExternalUrlObject.builder()
                                                    .spotify("spotify")
                                                    .build()
                                            )
                                            .href("href")
                                            .addImage(
                                                ImageObject.builder()
                                                    .height(300L)
                                                    .url(
                                                        "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                                    )
                                                    .width(300L)
                                                    .build()
                                            )
                                            .name("name")
                                            .releaseDate("1981-12")
                                            .releaseDatePrecision(
                                                TrackObject.Album.ReleaseDatePrecision.YEAR
                                            )
                                            .totalTracks(9L)
                                            .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                                            .restrictions(
                                                AlbumRestrictionObject.builder()
                                                    .reason(AlbumRestrictionObject.Reason.MARKET)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .addArtist(
                                        SimplifiedArtistObject.builder()
                                            .id("id")
                                            .externalUrls(
                                                ExternalUrlObject.builder()
                                                    .spotify("spotify")
                                                    .build()
                                            )
                                            .href("href")
                                            .name("name")
                                            .type(SimplifiedArtistObject.Type.ARTIST)
                                            .uri("uri")
                                            .build()
                                    )
                                    .addAvailableMarket("string")
                                    .discNumber(0L)
                                    .durationMs(0L)
                                    .explicit(true)
                                    .externalIds(
                                        ExternalIdObject.builder()
                                            .ean("ean")
                                            .isrc("isrc")
                                            .upc("upc")
                                            .build()
                                    )
                                    .externalUrls(
                                        ExternalUrlObject.builder().spotify("spotify").build()
                                    )
                                    .href("href")
                                    .isLocal(true)
                                    .isPlayable(true)
                                    .linkedFrom(
                                        LinkedTrackObject.builder()
                                            .id("id")
                                            .externalUrls(
                                                ExternalUrlObject.builder()
                                                    .spotify("spotify")
                                                    .build()
                                            )
                                            .href("href")
                                            .type("type")
                                            .uri("uri")
                                            .build()
                                    )
                                    .name("name")
                                    .popularity(0L)
                                    .previewUrl("preview_url")
                                    .restrictions(
                                        TrackRestrictionObject.builder().reason("reason").build()
                                    )
                                    .trackNumber(0L)
                                    .type(TrackObject.Type.TRACK)
                                    .uri("uri")
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(playlistRetrieveResponse.type()).isEqualTo("type")
        assertThat(playlistRetrieveResponse.uri()).isEqualTo("uri")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val playlistRetrieveResponse =
            PlaylistRetrieveResponse.builder()
                .id("id")
                .componentsSchemasPropertiesIsPublic(true)
                .collaborative(true)
                .description("description")
                .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                .followers(FollowersObject.builder().href("href").total(0L).build())
                .href("href")
                .addImage(
                    ImageObject.builder()
                        .height(300L)
                        .url("https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n")
                        .width(300L)
                        .build()
                )
                .name("name")
                .owner(
                    PlaylistRetrieveResponse.Owner.builder()
                        .id("id")
                        .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                        .href("href")
                        .type(PlaylistUserObject.Type.USER)
                        .uri("uri")
                        .displayName("display_name")
                        .build()
                )
                .snapshotId("snapshot_id")
                .tracks(
                    PlaylistRetrieveResponse.Tracks.builder()
                        .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                        .limit(20L)
                        .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .offset(0L)
                        .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .total(4L)
                        .addItem(
                            PlaylistTrackObject.builder()
                                .addedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .addedBy(
                                    PlaylistUserObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .type(PlaylistUserObject.Type.USER)
                                        .uri("uri")
                                        .build()
                                )
                                .isLocal(true)
                                .track(
                                    TrackObject.builder()
                                        .id("id")
                                        .album(
                                            TrackObject.Album.builder()
                                                .id("2up3OPMp9Tb4dAKM2erWXQ")
                                                .albumType(TrackObject.Album.AlbumType.COMPILATION)
                                                .addArtist(
                                                    SimplifiedArtistObject.builder()
                                                        .id("id")
                                                        .externalUrls(
                                                            ExternalUrlObject.builder()
                                                                .spotify("spotify")
                                                                .build()
                                                        )
                                                        .href("href")
                                                        .name("name")
                                                        .type(SimplifiedArtistObject.Type.ARTIST)
                                                        .uri("uri")
                                                        .build()
                                                )
                                                .availableMarkets(listOf("CA", "BR", "IT"))
                                                .externalUrls(
                                                    ExternalUrlObject.builder()
                                                        .spotify("spotify")
                                                        .build()
                                                )
                                                .href("href")
                                                .addImage(
                                                    ImageObject.builder()
                                                        .height(300L)
                                                        .url(
                                                            "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                                        )
                                                        .width(300L)
                                                        .build()
                                                )
                                                .name("name")
                                                .releaseDate("1981-12")
                                                .releaseDatePrecision(
                                                    TrackObject.Album.ReleaseDatePrecision.YEAR
                                                )
                                                .totalTracks(9L)
                                                .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                                                .restrictions(
                                                    AlbumRestrictionObject.builder()
                                                        .reason(
                                                            AlbumRestrictionObject.Reason.MARKET
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .addArtist(
                                            SimplifiedArtistObject.builder()
                                                .id("id")
                                                .externalUrls(
                                                    ExternalUrlObject.builder()
                                                        .spotify("spotify")
                                                        .build()
                                                )
                                                .href("href")
                                                .name("name")
                                                .type(SimplifiedArtistObject.Type.ARTIST)
                                                .uri("uri")
                                                .build()
                                        )
                                        .addAvailableMarket("string")
                                        .discNumber(0L)
                                        .durationMs(0L)
                                        .explicit(true)
                                        .externalIds(
                                            ExternalIdObject.builder()
                                                .ean("ean")
                                                .isrc("isrc")
                                                .upc("upc")
                                                .build()
                                        )
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .isLocal(true)
                                        .isPlayable(true)
                                        .linkedFrom(
                                            LinkedTrackObject.builder()
                                                .id("id")
                                                .externalUrls(
                                                    ExternalUrlObject.builder()
                                                        .spotify("spotify")
                                                        .build()
                                                )
                                                .href("href")
                                                .type("type")
                                                .uri("uri")
                                                .build()
                                        )
                                        .name("name")
                                        .popularity(0L)
                                        .previewUrl("preview_url")
                                        .restrictions(
                                            TrackRestrictionObject.builder()
                                                .reason("reason")
                                                .build()
                                        )
                                        .trackNumber(0L)
                                        .type(TrackObject.Type.TRACK)
                                        .uri("uri")
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .type("type")
                .uri("uri")
                .build()

        val roundtrippedPlaylistRetrieveResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(playlistRetrieveResponse),
                jacksonTypeRef<PlaylistRetrieveResponse>(),
            )

        assertThat(roundtrippedPlaylistRetrieveResponse).isEqualTo(playlistRetrieveResponse)
    }
}
