// File generated from our OpenAPI spec by Stainless.

package dev.cjav.spotted.models.me.albums

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import dev.cjav.spotted.core.jsonMapper
import dev.cjav.spotted.models.AlbumRestrictionObject
import dev.cjav.spotted.models.CopyrightObject
import dev.cjav.spotted.models.ExternalIdObject
import dev.cjav.spotted.models.ExternalUrlObject
import dev.cjav.spotted.models.ImageObject
import dev.cjav.spotted.models.LinkedTrackObject
import dev.cjav.spotted.models.SimplifiedArtistObject
import dev.cjav.spotted.models.SimplifiedTrackObject
import dev.cjav.spotted.models.TrackRestrictionObject
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AlbumListPageResponseTest {

    @Test
    fun create() {
        val albumListPageResponse =
            AlbumListPageResponse.builder()
                .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                .limit(20L)
                .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                .offset(0L)
                .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                .total(4L)
                .addItem(
                    AlbumListResponse.builder()
                        .addedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .album(
                            AlbumListResponse.Album.builder()
                                .id("2up3OPMp9Tb4dAKM2erWXQ")
                                .albumType(AlbumListResponse.Album.AlbumType.COMPILATION)
                                .availableMarkets(listOf("CA", "BR", "IT"))
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .addImage(
                                    ImageObject.builder()
                                        .height(300L)
                                        .url(
                                            "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                        )
                                        .width(300L)
                                        .build()
                                )
                                .name("name")
                                .releaseDate("1981-12")
                                .releaseDatePrecision(
                                    AlbumListResponse.Album.ReleaseDatePrecision.YEAR
                                )
                                .totalTracks(9L)
                                .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                                .addArtist(
                                    SimplifiedArtistObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .name("name")
                                        .type(SimplifiedArtistObject.Type.ARTIST)
                                        .uri("uri")
                                        .build()
                                )
                                .addCopyright(
                                    CopyrightObject.builder().text("text").type("type").build()
                                )
                                .externalIds(
                                    ExternalIdObject.builder()
                                        .ean("ean")
                                        .isrc("isrc")
                                        .upc("upc")
                                        .build()
                                )
                                .addGenre("string")
                                .label("label")
                                .popularity(0L)
                                .restrictions(
                                    AlbumRestrictionObject.builder()
                                        .reason(AlbumRestrictionObject.Reason.MARKET)
                                        .build()
                                )
                                .tracks(
                                    AlbumListResponse.Album.Tracks.builder()
                                        .href(
                                            "https://api.spotify.com/v1/me/shows?offset=0&limit=20\n"
                                        )
                                        .limit(20L)
                                        .next(
                                            "https://api.spotify.com/v1/me/shows?offset=1&limit=1"
                                        )
                                        .offset(0L)
                                        .previous(
                                            "https://api.spotify.com/v1/me/shows?offset=1&limit=1"
                                        )
                                        .total(4L)
                                        .addItem(
                                            SimplifiedTrackObject.builder()
                                                .id("id")
                                                .addArtist(
                                                    SimplifiedArtistObject.builder()
                                                        .id("id")
                                                        .externalUrls(
                                                            ExternalUrlObject.builder()
                                                                .spotify("spotify")
                                                                .build()
                                                        )
                                                        .href("href")
                                                        .name("name")
                                                        .type(SimplifiedArtistObject.Type.ARTIST)
                                                        .uri("uri")
                                                        .build()
                                                )
                                                .addAvailableMarket("string")
                                                .discNumber(0L)
                                                .durationMs(0L)
                                                .explicit(true)
                                                .externalUrls(
                                                    ExternalUrlObject.builder()
                                                        .spotify("spotify")
                                                        .build()
                                                )
                                                .href("href")
                                                .isLocal(true)
                                                .isPlayable(true)
                                                .linkedFrom(
                                                    LinkedTrackObject.builder()
                                                        .id("id")
                                                        .externalUrls(
                                                            ExternalUrlObject.builder()
                                                                .spotify("spotify")
                                                                .build()
                                                        )
                                                        .href("href")
                                                        .type("type")
                                                        .uri("uri")
                                                        .build()
                                                )
                                                .name("name")
                                                .previewUrl("preview_url")
                                                .restrictions(
                                                    TrackRestrictionObject.builder()
                                                        .reason("reason")
                                                        .build()
                                                )
                                                .trackNumber(0L)
                                                .type("type")
                                                .uri("uri")
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(albumListPageResponse.href())
            .isEqualTo("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
        assertThat(albumListPageResponse.limit()).isEqualTo(20L)
        assertThat(albumListPageResponse.next())
            .isEqualTo("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
        assertThat(albumListPageResponse.offset()).isEqualTo(0L)
        assertThat(albumListPageResponse.previous())
            .isEqualTo("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
        assertThat(albumListPageResponse.total()).isEqualTo(4L)
        assertThat(albumListPageResponse.items())
            .containsExactly(
                AlbumListResponse.builder()
                    .addedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .album(
                        AlbumListResponse.Album.builder()
                            .id("2up3OPMp9Tb4dAKM2erWXQ")
                            .albumType(AlbumListResponse.Album.AlbumType.COMPILATION)
                            .availableMarkets(listOf("CA", "BR", "IT"))
                            .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                            .href("href")
                            .addImage(
                                ImageObject.builder()
                                    .height(300L)
                                    .url(
                                        "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                    )
                                    .width(300L)
                                    .build()
                            )
                            .name("name")
                            .releaseDate("1981-12")
                            .releaseDatePrecision(AlbumListResponse.Album.ReleaseDatePrecision.YEAR)
                            .totalTracks(9L)
                            .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                            .addArtist(
                                SimplifiedArtistObject.builder()
                                    .id("id")
                                    .externalUrls(
                                        ExternalUrlObject.builder().spotify("spotify").build()
                                    )
                                    .href("href")
                                    .name("name")
                                    .type(SimplifiedArtistObject.Type.ARTIST)
                                    .uri("uri")
                                    .build()
                            )
                            .addCopyright(
                                CopyrightObject.builder().text("text").type("type").build()
                            )
                            .externalIds(
                                ExternalIdObject.builder()
                                    .ean("ean")
                                    .isrc("isrc")
                                    .upc("upc")
                                    .build()
                            )
                            .addGenre("string")
                            .label("label")
                            .popularity(0L)
                            .restrictions(
                                AlbumRestrictionObject.builder()
                                    .reason(AlbumRestrictionObject.Reason.MARKET)
                                    .build()
                            )
                            .tracks(
                                AlbumListResponse.Album.Tracks.builder()
                                    .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                                    .limit(20L)
                                    .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                                    .offset(0L)
                                    .previous(
                                        "https://api.spotify.com/v1/me/shows?offset=1&limit=1"
                                    )
                                    .total(4L)
                                    .addItem(
                                        SimplifiedTrackObject.builder()
                                            .id("id")
                                            .addArtist(
                                                SimplifiedArtistObject.builder()
                                                    .id("id")
                                                    .externalUrls(
                                                        ExternalUrlObject.builder()
                                                            .spotify("spotify")
                                                            .build()
                                                    )
                                                    .href("href")
                                                    .name("name")
                                                    .type(SimplifiedArtistObject.Type.ARTIST)
                                                    .uri("uri")
                                                    .build()
                                            )
                                            .addAvailableMarket("string")
                                            .discNumber(0L)
                                            .durationMs(0L)
                                            .explicit(true)
                                            .externalUrls(
                                                ExternalUrlObject.builder()
                                                    .spotify("spotify")
                                                    .build()
                                            )
                                            .href("href")
                                            .isLocal(true)
                                            .isPlayable(true)
                                            .linkedFrom(
                                                LinkedTrackObject.builder()
                                                    .id("id")
                                                    .externalUrls(
                                                        ExternalUrlObject.builder()
                                                            .spotify("spotify")
                                                            .build()
                                                    )
                                                    .href("href")
                                                    .type("type")
                                                    .uri("uri")
                                                    .build()
                                            )
                                            .name("name")
                                            .previewUrl("preview_url")
                                            .restrictions(
                                                TrackRestrictionObject.builder()
                                                    .reason("reason")
                                                    .build()
                                            )
                                            .trackNumber(0L)
                                            .type("type")
                                            .uri("uri")
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val albumListPageResponse =
            AlbumListPageResponse.builder()
                .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                .limit(20L)
                .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                .offset(0L)
                .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                .total(4L)
                .addItem(
                    AlbumListResponse.builder()
                        .addedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .album(
                            AlbumListResponse.Album.builder()
                                .id("2up3OPMp9Tb4dAKM2erWXQ")
                                .albumType(AlbumListResponse.Album.AlbumType.COMPILATION)
                                .availableMarkets(listOf("CA", "BR", "IT"))
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .addImage(
                                    ImageObject.builder()
                                        .height(300L)
                                        .url(
                                            "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                        )
                                        .width(300L)
                                        .build()
                                )
                                .name("name")
                                .releaseDate("1981-12")
                                .releaseDatePrecision(
                                    AlbumListResponse.Album.ReleaseDatePrecision.YEAR
                                )
                                .totalTracks(9L)
                                .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                                .addArtist(
                                    SimplifiedArtistObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .name("name")
                                        .type(SimplifiedArtistObject.Type.ARTIST)
                                        .uri("uri")
                                        .build()
                                )
                                .addCopyright(
                                    CopyrightObject.builder().text("text").type("type").build()
                                )
                                .externalIds(
                                    ExternalIdObject.builder()
                                        .ean("ean")
                                        .isrc("isrc")
                                        .upc("upc")
                                        .build()
                                )
                                .addGenre("string")
                                .label("label")
                                .popularity(0L)
                                .restrictions(
                                    AlbumRestrictionObject.builder()
                                        .reason(AlbumRestrictionObject.Reason.MARKET)
                                        .build()
                                )
                                .tracks(
                                    AlbumListResponse.Album.Tracks.builder()
                                        .href(
                                            "https://api.spotify.com/v1/me/shows?offset=0&limit=20\n"
                                        )
                                        .limit(20L)
                                        .next(
                                            "https://api.spotify.com/v1/me/shows?offset=1&limit=1"
                                        )
                                        .offset(0L)
                                        .previous(
                                            "https://api.spotify.com/v1/me/shows?offset=1&limit=1"
                                        )
                                        .total(4L)
                                        .addItem(
                                            SimplifiedTrackObject.builder()
                                                .id("id")
                                                .addArtist(
                                                    SimplifiedArtistObject.builder()
                                                        .id("id")
                                                        .externalUrls(
                                                            ExternalUrlObject.builder()
                                                                .spotify("spotify")
                                                                .build()
                                                        )
                                                        .href("href")
                                                        .name("name")
                                                        .type(SimplifiedArtistObject.Type.ARTIST)
                                                        .uri("uri")
                                                        .build()
                                                )
                                                .addAvailableMarket("string")
                                                .discNumber(0L)
                                                .durationMs(0L)
                                                .explicit(true)
                                                .externalUrls(
                                                    ExternalUrlObject.builder()
                                                        .spotify("spotify")
                                                        .build()
                                                )
                                                .href("href")
                                                .isLocal(true)
                                                .isPlayable(true)
                                                .linkedFrom(
                                                    LinkedTrackObject.builder()
                                                        .id("id")
                                                        .externalUrls(
                                                            ExternalUrlObject.builder()
                                                                .spotify("spotify")
                                                                .build()
                                                        )
                                                        .href("href")
                                                        .type("type")
                                                        .uri("uri")
                                                        .build()
                                                )
                                                .name("name")
                                                .previewUrl("preview_url")
                                                .restrictions(
                                                    TrackRestrictionObject.builder()
                                                        .reason("reason")
                                                        .build()
                                                )
                                                .trackNumber(0L)
                                                .type("type")
                                                .uri("uri")
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedAlbumListPageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(albumListPageResponse),
                jacksonTypeRef<AlbumListPageResponse>(),
            )

        assertThat(roundtrippedAlbumListPageResponse).isEqualTo(albumListPageResponse)
    }
}
