// File generated from our OpenAPI spec by Stainless.

package com.spotted.api.models.albums

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.spotted.api.core.jsonMapper
import com.spotted.api.models.AlbumRestrictionObject
import com.spotted.api.models.CopyrightObject
import com.spotted.api.models.ExternalIdObject
import com.spotted.api.models.ExternalUrlObject
import com.spotted.api.models.ImageObject
import com.spotted.api.models.LinkedTrackObject
import com.spotted.api.models.SimplifiedArtistObject
import com.spotted.api.models.SimplifiedTrackObject
import com.spotted.api.models.TrackRestrictionObject
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AlbumBulkRetrieveResponseTest {

    @Test
    fun create() {
        val albumBulkRetrieveResponse =
            AlbumBulkRetrieveResponse.builder()
                .addAlbum(
                    AlbumBulkRetrieveResponse.Album.builder()
                        .id("2up3OPMp9Tb4dAKM2erWXQ")
                        .albumType(AlbumBulkRetrieveResponse.Album.AlbumType.COMPILATION)
                        .availableMarkets(listOf("CA", "BR", "IT"))
                        .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                        .href("href")
                        .addImage(
                            ImageObject.builder()
                                .height(300L)
                                .url(
                                    "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                )
                                .width(300L)
                                .build()
                        )
                        .name("name")
                        .releaseDate("1981-12")
                        .releaseDatePrecision(
                            AlbumBulkRetrieveResponse.Album.ReleaseDatePrecision.YEAR
                        )
                        .totalTracks(9L)
                        .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                        .addArtist(
                            SimplifiedArtistObject.builder()
                                .id("id")
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .name("name")
                                .type(SimplifiedArtistObject.Type.ARTIST)
                                .uri("uri")
                                .build()
                        )
                        .addCopyright(CopyrightObject.builder().text("text").type("type").build())
                        .externalIds(
                            ExternalIdObject.builder().ean("ean").isrc("isrc").upc("upc").build()
                        )
                        .addGenre("string")
                        .label("label")
                        .popularity(0L)
                        .restrictions(
                            AlbumRestrictionObject.builder()
                                .reason(AlbumRestrictionObject.Reason.MARKET)
                                .build()
                        )
                        .tracks(
                            AlbumBulkRetrieveResponse.Album.Tracks.builder()
                                .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                                .limit(20L)
                                .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                                .offset(0L)
                                .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                                .total(4L)
                                .addItem(
                                    SimplifiedTrackObject.builder()
                                        .id("id")
                                        .addArtist(
                                            SimplifiedArtistObject.builder()
                                                .id("id")
                                                .externalUrls(
                                                    ExternalUrlObject.builder()
                                                        .spotify("spotify")
                                                        .build()
                                                )
                                                .href("href")
                                                .name("name")
                                                .type(SimplifiedArtistObject.Type.ARTIST)
                                                .uri("uri")
                                                .build()
                                        )
                                        .addAvailableMarket("string")
                                        .discNumber(0L)
                                        .durationMs(0L)
                                        .explicit(true)
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .isLocal(true)
                                        .isPlayable(true)
                                        .linkedFrom(
                                            LinkedTrackObject.builder()
                                                .id("id")
                                                .externalUrls(
                                                    ExternalUrlObject.builder()
                                                        .spotify("spotify")
                                                        .build()
                                                )
                                                .href("href")
                                                .type("type")
                                                .uri("uri")
                                                .build()
                                        )
                                        .name("name")
                                        .previewUrl("preview_url")
                                        .restrictions(
                                            TrackRestrictionObject.builder()
                                                .reason("reason")
                                                .build()
                                        )
                                        .trackNumber(0L)
                                        .type("type")
                                        .uri("uri")
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(albumBulkRetrieveResponse.albums())
            .containsExactly(
                AlbumBulkRetrieveResponse.Album.builder()
                    .id("2up3OPMp9Tb4dAKM2erWXQ")
                    .albumType(AlbumBulkRetrieveResponse.Album.AlbumType.COMPILATION)
                    .availableMarkets(listOf("CA", "BR", "IT"))
                    .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                    .href("href")
                    .addImage(
                        ImageObject.builder()
                            .height(300L)
                            .url(
                                "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                            )
                            .width(300L)
                            .build()
                    )
                    .name("name")
                    .releaseDate("1981-12")
                    .releaseDatePrecision(AlbumBulkRetrieveResponse.Album.ReleaseDatePrecision.YEAR)
                    .totalTracks(9L)
                    .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                    .addArtist(
                        SimplifiedArtistObject.builder()
                            .id("id")
                            .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                            .href("href")
                            .name("name")
                            .type(SimplifiedArtistObject.Type.ARTIST)
                            .uri("uri")
                            .build()
                    )
                    .addCopyright(CopyrightObject.builder().text("text").type("type").build())
                    .externalIds(
                        ExternalIdObject.builder().ean("ean").isrc("isrc").upc("upc").build()
                    )
                    .addGenre("string")
                    .label("label")
                    .popularity(0L)
                    .restrictions(
                        AlbumRestrictionObject.builder()
                            .reason(AlbumRestrictionObject.Reason.MARKET)
                            .build()
                    )
                    .tracks(
                        AlbumBulkRetrieveResponse.Album.Tracks.builder()
                            .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                            .limit(20L)
                            .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                            .offset(0L)
                            .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                            .total(4L)
                            .addItem(
                                SimplifiedTrackObject.builder()
                                    .id("id")
                                    .addArtist(
                                        SimplifiedArtistObject.builder()
                                            .id("id")
                                            .externalUrls(
                                                ExternalUrlObject.builder()
                                                    .spotify("spotify")
                                                    .build()
                                            )
                                            .href("href")
                                            .name("name")
                                            .type(SimplifiedArtistObject.Type.ARTIST)
                                            .uri("uri")
                                            .build()
                                    )
                                    .addAvailableMarket("string")
                                    .discNumber(0L)
                                    .durationMs(0L)
                                    .explicit(true)
                                    .externalUrls(
                                        ExternalUrlObject.builder().spotify("spotify").build()
                                    )
                                    .href("href")
                                    .isLocal(true)
                                    .isPlayable(true)
                                    .linkedFrom(
                                        LinkedTrackObject.builder()
                                            .id("id")
                                            .externalUrls(
                                                ExternalUrlObject.builder()
                                                    .spotify("spotify")
                                                    .build()
                                            )
                                            .href("href")
                                            .type("type")
                                            .uri("uri")
                                            .build()
                                    )
                                    .name("name")
                                    .previewUrl("preview_url")
                                    .restrictions(
                                        TrackRestrictionObject.builder().reason("reason").build()
                                    )
                                    .trackNumber(0L)
                                    .type("type")
                                    .uri("uri")
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val albumBulkRetrieveResponse =
            AlbumBulkRetrieveResponse.builder()
                .addAlbum(
                    AlbumBulkRetrieveResponse.Album.builder()
                        .id("2up3OPMp9Tb4dAKM2erWXQ")
                        .albumType(AlbumBulkRetrieveResponse.Album.AlbumType.COMPILATION)
                        .availableMarkets(listOf("CA", "BR", "IT"))
                        .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                        .href("href")
                        .addImage(
                            ImageObject.builder()
                                .height(300L)
                                .url(
                                    "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                )
                                .width(300L)
                                .build()
                        )
                        .name("name")
                        .releaseDate("1981-12")
                        .releaseDatePrecision(
                            AlbumBulkRetrieveResponse.Album.ReleaseDatePrecision.YEAR
                        )
                        .totalTracks(9L)
                        .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                        .addArtist(
                            SimplifiedArtistObject.builder()
                                .id("id")
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .name("name")
                                .type(SimplifiedArtistObject.Type.ARTIST)
                                .uri("uri")
                                .build()
                        )
                        .addCopyright(CopyrightObject.builder().text("text").type("type").build())
                        .externalIds(
                            ExternalIdObject.builder().ean("ean").isrc("isrc").upc("upc").build()
                        )
                        .addGenre("string")
                        .label("label")
                        .popularity(0L)
                        .restrictions(
                            AlbumRestrictionObject.builder()
                                .reason(AlbumRestrictionObject.Reason.MARKET)
                                .build()
                        )
                        .tracks(
                            AlbumBulkRetrieveResponse.Album.Tracks.builder()
                                .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                                .limit(20L)
                                .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                                .offset(0L)
                                .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                                .total(4L)
                                .addItem(
                                    SimplifiedTrackObject.builder()
                                        .id("id")
                                        .addArtist(
                                            SimplifiedArtistObject.builder()
                                                .id("id")
                                                .externalUrls(
                                                    ExternalUrlObject.builder()
                                                        .spotify("spotify")
                                                        .build()
                                                )
                                                .href("href")
                                                .name("name")
                                                .type(SimplifiedArtistObject.Type.ARTIST)
                                                .uri("uri")
                                                .build()
                                        )
                                        .addAvailableMarket("string")
                                        .discNumber(0L)
                                        .durationMs(0L)
                                        .explicit(true)
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .isLocal(true)
                                        .isPlayable(true)
                                        .linkedFrom(
                                            LinkedTrackObject.builder()
                                                .id("id")
                                                .externalUrls(
                                                    ExternalUrlObject.builder()
                                                        .spotify("spotify")
                                                        .build()
                                                )
                                                .href("href")
                                                .type("type")
                                                .uri("uri")
                                                .build()
                                        )
                                        .name("name")
                                        .previewUrl("preview_url")
                                        .restrictions(
                                            TrackRestrictionObject.builder()
                                                .reason("reason")
                                                .build()
                                        )
                                        .trackNumber(0L)
                                        .type("type")
                                        .uri("uri")
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedAlbumBulkRetrieveResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(albumBulkRetrieveResponse),
                jacksonTypeRef<AlbumBulkRetrieveResponse>(),
            )

        assertThat(roundtrippedAlbumBulkRetrieveResponse).isEqualTo(albumBulkRetrieveResponse)
    }
}
