// File generated from our OpenAPI spec by Stainless.

package dev.cjav.spotted.models.me.player

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import dev.cjav.spotted.core.jsonMapper
import dev.cjav.spotted.models.AlbumRestrictionObject
import dev.cjav.spotted.models.ExternalIdObject
import dev.cjav.spotted.models.ExternalUrlObject
import dev.cjav.spotted.models.ImageObject
import dev.cjav.spotted.models.LinkedTrackObject
import dev.cjav.spotted.models.SimplifiedArtistObject
import dev.cjav.spotted.models.TrackObject
import dev.cjav.spotted.models.TrackRestrictionObject
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PlayerListRecentlyPlayedPageResponseTest {

    @Test
    fun create() {
        val playerListRecentlyPlayedPageResponse =
            PlayerListRecentlyPlayedPageResponse.builder()
                .cursors(
                    PlayerListRecentlyPlayedPageResponse.Cursors.builder()
                        .after("after")
                        .before("before")
                        .published(true)
                        .build()
                )
                .href("href")
                .addItem(
                    PlayerListRecentlyPlayedResponse.builder()
                        .context(
                            ContextObject.builder()
                                .externalUrls(
                                    ExternalUrlObject.builder()
                                        .published(true)
                                        .spotify("spotify")
                                        .build()
                                )
                                .href("href")
                                .published(true)
                                .type("type")
                                .uri("uri")
                                .build()
                        )
                        .playedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .published(true)
                        .track(
                            TrackObject.builder()
                                .id("id")
                                .album(
                                    TrackObject.Album.builder()
                                        .id("2up3OPMp9Tb4dAKM2erWXQ")
                                        .albumType(TrackObject.Album.AlbumType.COMPILATION)
                                        .addArtist(
                                            SimplifiedArtistObject.builder()
                                                .id("id")
                                                .externalUrls(
                                                    ExternalUrlObject.builder()
                                                        .published(true)
                                                        .spotify("spotify")
                                                        .build()
                                                )
                                                .href("href")
                                                .name("name")
                                                .published(true)
                                                .type(SimplifiedArtistObject.Type.ARTIST)
                                                .uri("uri")
                                                .build()
                                        )
                                        .availableMarkets(listOf("CA", "BR", "IT"))
                                        .externalUrls(
                                            ExternalUrlObject.builder()
                                                .published(true)
                                                .spotify("spotify")
                                                .build()
                                        )
                                        .href("href")
                                        .addImage(
                                            ImageObject.builder()
                                                .height(300L)
                                                .url(
                                                    "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                                )
                                                .width(300L)
                                                .published(true)
                                                .build()
                                        )
                                        .name("name")
                                        .releaseDate("1981-12")
                                        .releaseDatePrecision(
                                            TrackObject.Album.ReleaseDatePrecision.YEAR
                                        )
                                        .totalTracks(9L)
                                        .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                                        .published(true)
                                        .restrictions(
                                            AlbumRestrictionObject.builder()
                                                .published(true)
                                                .reason(AlbumRestrictionObject.Reason.MARKET)
                                                .build()
                                        )
                                        .build()
                                )
                                .addArtist(
                                    SimplifiedArtistObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder()
                                                .published(true)
                                                .spotify("spotify")
                                                .build()
                                        )
                                        .href("href")
                                        .name("name")
                                        .published(true)
                                        .type(SimplifiedArtistObject.Type.ARTIST)
                                        .uri("uri")
                                        .build()
                                )
                                .addAvailableMarket("string")
                                .discNumber(0L)
                                .durationMs(0L)
                                .explicit(true)
                                .externalIds(
                                    ExternalIdObject.builder()
                                        .ean("ean")
                                        .isrc("isrc")
                                        .published(true)
                                        .upc("upc")
                                        .build()
                                )
                                .externalUrls(
                                    ExternalUrlObject.builder()
                                        .published(true)
                                        .spotify("spotify")
                                        .build()
                                )
                                .href("href")
                                .isLocal(true)
                                .isPlayable(true)
                                .linkedFrom(
                                    LinkedTrackObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder()
                                                .published(true)
                                                .spotify("spotify")
                                                .build()
                                        )
                                        .href("href")
                                        .published(true)
                                        .type("type")
                                        .uri("uri")
                                        .build()
                                )
                                .name("name")
                                .popularity(0L)
                                .previewUrl("preview_url")
                                .published(true)
                                .restrictions(
                                    TrackRestrictionObject.builder()
                                        .published(true)
                                        .reason("reason")
                                        .build()
                                )
                                .trackNumber(0L)
                                .type(TrackObject.Type.TRACK)
                                .uri("uri")
                                .build()
                        )
                        .build()
                )
                .limit(0L)
                .next("next")
                .published(true)
                .total(0L)
                .build()

        assertThat(playerListRecentlyPlayedPageResponse.cursors())
            .isEqualTo(
                PlayerListRecentlyPlayedPageResponse.Cursors.builder()
                    .after("after")
                    .before("before")
                    .published(true)
                    .build()
            )
        assertThat(playerListRecentlyPlayedPageResponse.href()).isEqualTo("href")
        assertThat(playerListRecentlyPlayedPageResponse.items())
            .containsExactly(
                PlayerListRecentlyPlayedResponse.builder()
                    .context(
                        ContextObject.builder()
                            .externalUrls(
                                ExternalUrlObject.builder()
                                    .published(true)
                                    .spotify("spotify")
                                    .build()
                            )
                            .href("href")
                            .published(true)
                            .type("type")
                            .uri("uri")
                            .build()
                    )
                    .playedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .published(true)
                    .track(
                        TrackObject.builder()
                            .id("id")
                            .album(
                                TrackObject.Album.builder()
                                    .id("2up3OPMp9Tb4dAKM2erWXQ")
                                    .albumType(TrackObject.Album.AlbumType.COMPILATION)
                                    .addArtist(
                                        SimplifiedArtistObject.builder()
                                            .id("id")
                                            .externalUrls(
                                                ExternalUrlObject.builder()
                                                    .published(true)
                                                    .spotify("spotify")
                                                    .build()
                                            )
                                            .href("href")
                                            .name("name")
                                            .published(true)
                                            .type(SimplifiedArtistObject.Type.ARTIST)
                                            .uri("uri")
                                            .build()
                                    )
                                    .availableMarkets(listOf("CA", "BR", "IT"))
                                    .externalUrls(
                                        ExternalUrlObject.builder()
                                            .published(true)
                                            .spotify("spotify")
                                            .build()
                                    )
                                    .href("href")
                                    .addImage(
                                        ImageObject.builder()
                                            .height(300L)
                                            .url(
                                                "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                            )
                                            .width(300L)
                                            .published(true)
                                            .build()
                                    )
                                    .name("name")
                                    .releaseDate("1981-12")
                                    .releaseDatePrecision(
                                        TrackObject.Album.ReleaseDatePrecision.YEAR
                                    )
                                    .totalTracks(9L)
                                    .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                                    .published(true)
                                    .restrictions(
                                        AlbumRestrictionObject.builder()
                                            .published(true)
                                            .reason(AlbumRestrictionObject.Reason.MARKET)
                                            .build()
                                    )
                                    .build()
                            )
                            .addArtist(
                                SimplifiedArtistObject.builder()
                                    .id("id")
                                    .externalUrls(
                                        ExternalUrlObject.builder()
                                            .published(true)
                                            .spotify("spotify")
                                            .build()
                                    )
                                    .href("href")
                                    .name("name")
                                    .published(true)
                                    .type(SimplifiedArtistObject.Type.ARTIST)
                                    .uri("uri")
                                    .build()
                            )
                            .addAvailableMarket("string")
                            .discNumber(0L)
                            .durationMs(0L)
                            .explicit(true)
                            .externalIds(
                                ExternalIdObject.builder()
                                    .ean("ean")
                                    .isrc("isrc")
                                    .published(true)
                                    .upc("upc")
                                    .build()
                            )
                            .externalUrls(
                                ExternalUrlObject.builder()
                                    .published(true)
                                    .spotify("spotify")
                                    .build()
                            )
                            .href("href")
                            .isLocal(true)
                            .isPlayable(true)
                            .linkedFrom(
                                LinkedTrackObject.builder()
                                    .id("id")
                                    .externalUrls(
                                        ExternalUrlObject.builder()
                                            .published(true)
                                            .spotify("spotify")
                                            .build()
                                    )
                                    .href("href")
                                    .published(true)
                                    .type("type")
                                    .uri("uri")
                                    .build()
                            )
                            .name("name")
                            .popularity(0L)
                            .previewUrl("preview_url")
                            .published(true)
                            .restrictions(
                                TrackRestrictionObject.builder()
                                    .published(true)
                                    .reason("reason")
                                    .build()
                            )
                            .trackNumber(0L)
                            .type(TrackObject.Type.TRACK)
                            .uri("uri")
                            .build()
                    )
                    .build()
            )
        assertThat(playerListRecentlyPlayedPageResponse.limit()).isEqualTo(0L)
        assertThat(playerListRecentlyPlayedPageResponse.next()).isEqualTo("next")
        assertThat(playerListRecentlyPlayedPageResponse.published()).isEqualTo(true)
        assertThat(playerListRecentlyPlayedPageResponse.total()).isEqualTo(0L)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val playerListRecentlyPlayedPageResponse =
            PlayerListRecentlyPlayedPageResponse.builder()
                .cursors(
                    PlayerListRecentlyPlayedPageResponse.Cursors.builder()
                        .after("after")
                        .before("before")
                        .published(true)
                        .build()
                )
                .href("href")
                .addItem(
                    PlayerListRecentlyPlayedResponse.builder()
                        .context(
                            ContextObject.builder()
                                .externalUrls(
                                    ExternalUrlObject.builder()
                                        .published(true)
                                        .spotify("spotify")
                                        .build()
                                )
                                .href("href")
                                .published(true)
                                .type("type")
                                .uri("uri")
                                .build()
                        )
                        .playedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .published(true)
                        .track(
                            TrackObject.builder()
                                .id("id")
                                .album(
                                    TrackObject.Album.builder()
                                        .id("2up3OPMp9Tb4dAKM2erWXQ")
                                        .albumType(TrackObject.Album.AlbumType.COMPILATION)
                                        .addArtist(
                                            SimplifiedArtistObject.builder()
                                                .id("id")
                                                .externalUrls(
                                                    ExternalUrlObject.builder()
                                                        .published(true)
                                                        .spotify("spotify")
                                                        .build()
                                                )
                                                .href("href")
                                                .name("name")
                                                .published(true)
                                                .type(SimplifiedArtistObject.Type.ARTIST)
                                                .uri("uri")
                                                .build()
                                        )
                                        .availableMarkets(listOf("CA", "BR", "IT"))
                                        .externalUrls(
                                            ExternalUrlObject.builder()
                                                .published(true)
                                                .spotify("spotify")
                                                .build()
                                        )
                                        .href("href")
                                        .addImage(
                                            ImageObject.builder()
                                                .height(300L)
                                                .url(
                                                    "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                                )
                                                .width(300L)
                                                .published(true)
                                                .build()
                                        )
                                        .name("name")
                                        .releaseDate("1981-12")
                                        .releaseDatePrecision(
                                            TrackObject.Album.ReleaseDatePrecision.YEAR
                                        )
                                        .totalTracks(9L)
                                        .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                                        .published(true)
                                        .restrictions(
                                            AlbumRestrictionObject.builder()
                                                .published(true)
                                                .reason(AlbumRestrictionObject.Reason.MARKET)
                                                .build()
                                        )
                                        .build()
                                )
                                .addArtist(
                                    SimplifiedArtistObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder()
                                                .published(true)
                                                .spotify("spotify")
                                                .build()
                                        )
                                        .href("href")
                                        .name("name")
                                        .published(true)
                                        .type(SimplifiedArtistObject.Type.ARTIST)
                                        .uri("uri")
                                        .build()
                                )
                                .addAvailableMarket("string")
                                .discNumber(0L)
                                .durationMs(0L)
                                .explicit(true)
                                .externalIds(
                                    ExternalIdObject.builder()
                                        .ean("ean")
                                        .isrc("isrc")
                                        .published(true)
                                        .upc("upc")
                                        .build()
                                )
                                .externalUrls(
                                    ExternalUrlObject.builder()
                                        .published(true)
                                        .spotify("spotify")
                                        .build()
                                )
                                .href("href")
                                .isLocal(true)
                                .isPlayable(true)
                                .linkedFrom(
                                    LinkedTrackObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder()
                                                .published(true)
                                                .spotify("spotify")
                                                .build()
                                        )
                                        .href("href")
                                        .published(true)
                                        .type("type")
                                        .uri("uri")
                                        .build()
                                )
                                .name("name")
                                .popularity(0L)
                                .previewUrl("preview_url")
                                .published(true)
                                .restrictions(
                                    TrackRestrictionObject.builder()
                                        .published(true)
                                        .reason("reason")
                                        .build()
                                )
                                .trackNumber(0L)
                                .type(TrackObject.Type.TRACK)
                                .uri("uri")
                                .build()
                        )
                        .build()
                )
                .limit(0L)
                .next("next")
                .published(true)
                .total(0L)
                .build()

        val roundtrippedPlayerListRecentlyPlayedPageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(playerListRecentlyPlayedPageResponse),
                jacksonTypeRef<PlayerListRecentlyPlayedPageResponse>(),
            )

        assertThat(roundtrippedPlayerListRecentlyPlayedPageResponse)
            .isEqualTo(playerListRecentlyPlayedPageResponse)
    }
}
