// File generated from our OpenAPI spec by Stainless.

package dev.cjav.spotted.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import dev.cjav.spotted.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TrackObjectTest {

    @Test
    fun create() {
        val trackObject =
            TrackObject.builder()
                .id("id")
                .album(
                    TrackObject.Album.builder()
                        .id("2up3OPMp9Tb4dAKM2erWXQ")
                        .albumType(TrackObject.Album.AlbumType.COMPILATION)
                        .addArtist(
                            SimplifiedArtistObject.builder()
                                .id("id")
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .name("name")
                                .type(SimplifiedArtistObject.Type.ARTIST)
                                .uri("uri")
                                .build()
                        )
                        .availableMarkets(listOf("CA", "BR", "IT"))
                        .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                        .href("href")
                        .addImage(
                            ImageObject.builder()
                                .height(300L)
                                .url(
                                    "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                )
                                .width(300L)
                                .build()
                        )
                        .name("name")
                        .releaseDate("1981-12")
                        .releaseDatePrecision(TrackObject.Album.ReleaseDatePrecision.YEAR)
                        .totalTracks(9L)
                        .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                        .restrictions(
                            AlbumRestrictionObject.builder()
                                .reason(AlbumRestrictionObject.Reason.MARKET)
                                .build()
                        )
                        .build()
                )
                .addArtist(
                    SimplifiedArtistObject.builder()
                        .id("id")
                        .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                        .href("href")
                        .name("name")
                        .type(SimplifiedArtistObject.Type.ARTIST)
                        .uri("uri")
                        .build()
                )
                .addAvailableMarket("string")
                .discNumber(0L)
                .durationMs(0L)
                .explicit(true)
                .externalIds(ExternalIdObject.builder().ean("ean").isrc("isrc").upc("upc").build())
                .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                .href("href")
                .isLocal(true)
                .isPlayable(true)
                .linkedFrom(
                    LinkedTrackObject.builder()
                        .id("id")
                        .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                        .href("href")
                        .type("type")
                        .uri("uri")
                        .build()
                )
                .name("name")
                .popularity(0L)
                .previewUrl("preview_url")
                .restrictions(TrackRestrictionObject.builder().reason("reason").build())
                .trackNumber(0L)
                .type(TrackObject.Type.TRACK)
                .uri("uri")
                .build()

        assertThat(trackObject.id()).isEqualTo("id")
        assertThat(trackObject.album())
            .isEqualTo(
                TrackObject.Album.builder()
                    .id("2up3OPMp9Tb4dAKM2erWXQ")
                    .albumType(TrackObject.Album.AlbumType.COMPILATION)
                    .addArtist(
                        SimplifiedArtistObject.builder()
                            .id("id")
                            .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                            .href("href")
                            .name("name")
                            .type(SimplifiedArtistObject.Type.ARTIST)
                            .uri("uri")
                            .build()
                    )
                    .availableMarkets(listOf("CA", "BR", "IT"))
                    .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                    .href("href")
                    .addImage(
                        ImageObject.builder()
                            .height(300L)
                            .url(
                                "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                            )
                            .width(300L)
                            .build()
                    )
                    .name("name")
                    .releaseDate("1981-12")
                    .releaseDatePrecision(TrackObject.Album.ReleaseDatePrecision.YEAR)
                    .totalTracks(9L)
                    .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                    .restrictions(
                        AlbumRestrictionObject.builder()
                            .reason(AlbumRestrictionObject.Reason.MARKET)
                            .build()
                    )
                    .build()
            )
        assertThat(trackObject.artists())
            .containsExactly(
                SimplifiedArtistObject.builder()
                    .id("id")
                    .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                    .href("href")
                    .name("name")
                    .type(SimplifiedArtistObject.Type.ARTIST)
                    .uri("uri")
                    .build()
            )
        assertThat(trackObject.availableMarkets()).containsExactly("string")
        assertThat(trackObject.discNumber()).isEqualTo(0L)
        assertThat(trackObject.durationMs()).isEqualTo(0L)
        assertThat(trackObject.explicit()).isEqualTo(true)
        assertThat(trackObject.externalIds())
            .isEqualTo(ExternalIdObject.builder().ean("ean").isrc("isrc").upc("upc").build())
        assertThat(trackObject.externalUrls())
            .isEqualTo(ExternalUrlObject.builder().spotify("spotify").build())
        assertThat(trackObject.href()).isEqualTo("href")
        assertThat(trackObject.isLocal()).isEqualTo(true)
        assertThat(trackObject.isPlayable()).isEqualTo(true)
        assertThat(trackObject.linkedFrom())
            .isEqualTo(
                LinkedTrackObject.builder()
                    .id("id")
                    .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                    .href("href")
                    .type("type")
                    .uri("uri")
                    .build()
            )
        assertThat(trackObject.name()).isEqualTo("name")
        assertThat(trackObject.popularity()).isEqualTo(0L)
        assertThat(trackObject.previewUrl()).isEqualTo("preview_url")
        assertThat(trackObject.restrictions())
            .isEqualTo(TrackRestrictionObject.builder().reason("reason").build())
        assertThat(trackObject.trackNumber()).isEqualTo(0L)
        assertThat(trackObject.type()).isEqualTo(TrackObject.Type.TRACK)
        assertThat(trackObject.uri()).isEqualTo("uri")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val trackObject =
            TrackObject.builder()
                .id("id")
                .album(
                    TrackObject.Album.builder()
                        .id("2up3OPMp9Tb4dAKM2erWXQ")
                        .albumType(TrackObject.Album.AlbumType.COMPILATION)
                        .addArtist(
                            SimplifiedArtistObject.builder()
                                .id("id")
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .name("name")
                                .type(SimplifiedArtistObject.Type.ARTIST)
                                .uri("uri")
                                .build()
                        )
                        .availableMarkets(listOf("CA", "BR", "IT"))
                        .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                        .href("href")
                        .addImage(
                            ImageObject.builder()
                                .height(300L)
                                .url(
                                    "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                )
                                .width(300L)
                                .build()
                        )
                        .name("name")
                        .releaseDate("1981-12")
                        .releaseDatePrecision(TrackObject.Album.ReleaseDatePrecision.YEAR)
                        .totalTracks(9L)
                        .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                        .restrictions(
                            AlbumRestrictionObject.builder()
                                .reason(AlbumRestrictionObject.Reason.MARKET)
                                .build()
                        )
                        .build()
                )
                .addArtist(
                    SimplifiedArtistObject.builder()
                        .id("id")
                        .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                        .href("href")
                        .name("name")
                        .type(SimplifiedArtistObject.Type.ARTIST)
                        .uri("uri")
                        .build()
                )
                .addAvailableMarket("string")
                .discNumber(0L)
                .durationMs(0L)
                .explicit(true)
                .externalIds(ExternalIdObject.builder().ean("ean").isrc("isrc").upc("upc").build())
                .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                .href("href")
                .isLocal(true)
                .isPlayable(true)
                .linkedFrom(
                    LinkedTrackObject.builder()
                        .id("id")
                        .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                        .href("href")
                        .type("type")
                        .uri("uri")
                        .build()
                )
                .name("name")
                .popularity(0L)
                .previewUrl("preview_url")
                .restrictions(TrackRestrictionObject.builder().reason("reason").build())
                .trackNumber(0L)
                .type(TrackObject.Type.TRACK)
                .uri("uri")
                .build()

        val roundtrippedTrackObject =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(trackObject),
                jacksonTypeRef<TrackObject>(),
            )

        assertThat(roundtrippedTrackObject).isEqualTo(trackObject)
    }
}
