// File generated from our OpenAPI spec by Stainless.

package dev.cjav.spotted.models.recommendations

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import dev.cjav.spotted.core.jsonMapper
import dev.cjav.spotted.models.AlbumRestrictionObject
import dev.cjav.spotted.models.ExternalIdObject
import dev.cjav.spotted.models.ExternalUrlObject
import dev.cjav.spotted.models.ImageObject
import dev.cjav.spotted.models.LinkedTrackObject
import dev.cjav.spotted.models.SimplifiedArtistObject
import dev.cjav.spotted.models.TrackObject
import dev.cjav.spotted.models.TrackRestrictionObject
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class RecommendationGetResponseTest {

    @Test
    fun create() {
        val recommendationGetResponse =
            RecommendationGetResponse.builder()
                .addSeed(
                    RecommendationGetResponse.Seed.builder()
                        .id("id")
                        .afterFilteringSize(0L)
                        .afterRelinkingSize(0L)
                        .href("href")
                        .initialPoolSize(0L)
                        .type("type")
                        .build()
                )
                .addTrack(
                    TrackObject.builder()
                        .id("id")
                        .album(
                            TrackObject.Album.builder()
                                .id("2up3OPMp9Tb4dAKM2erWXQ")
                                .albumType(TrackObject.Album.AlbumType.COMPILATION)
                                .addArtist(
                                    SimplifiedArtistObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .name("name")
                                        .type(SimplifiedArtistObject.Type.ARTIST)
                                        .uri("uri")
                                        .build()
                                )
                                .availableMarkets(listOf("CA", "BR", "IT"))
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .addImage(
                                    ImageObject.builder()
                                        .height(300L)
                                        .url(
                                            "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                        )
                                        .width(300L)
                                        .build()
                                )
                                .name("name")
                                .releaseDate("1981-12")
                                .releaseDatePrecision(TrackObject.Album.ReleaseDatePrecision.YEAR)
                                .totalTracks(9L)
                                .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                                .restrictions(
                                    AlbumRestrictionObject.builder()
                                        .reason(AlbumRestrictionObject.Reason.MARKET)
                                        .build()
                                )
                                .build()
                        )
                        .addArtist(
                            SimplifiedArtistObject.builder()
                                .id("id")
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .name("name")
                                .type(SimplifiedArtistObject.Type.ARTIST)
                                .uri("uri")
                                .build()
                        )
                        .addAvailableMarket("string")
                        .discNumber(0L)
                        .durationMs(0L)
                        .explicit(true)
                        .externalIds(
                            ExternalIdObject.builder().ean("ean").isrc("isrc").upc("upc").build()
                        )
                        .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                        .href("href")
                        .isLocal(true)
                        .isPlayable(true)
                        .linkedFrom(
                            LinkedTrackObject.builder()
                                .id("id")
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .type("type")
                                .uri("uri")
                                .build()
                        )
                        .name("name")
                        .popularity(0L)
                        .previewUrl("preview_url")
                        .restrictions(TrackRestrictionObject.builder().reason("reason").build())
                        .trackNumber(0L)
                        .type(TrackObject.Type.TRACK)
                        .uri("uri")
                        .build()
                )
                .build()

        assertThat(recommendationGetResponse.seeds())
            .containsExactly(
                RecommendationGetResponse.Seed.builder()
                    .id("id")
                    .afterFilteringSize(0L)
                    .afterRelinkingSize(0L)
                    .href("href")
                    .initialPoolSize(0L)
                    .type("type")
                    .build()
            )
        assertThat(recommendationGetResponse.tracks())
            .containsExactly(
                TrackObject.builder()
                    .id("id")
                    .album(
                        TrackObject.Album.builder()
                            .id("2up3OPMp9Tb4dAKM2erWXQ")
                            .albumType(TrackObject.Album.AlbumType.COMPILATION)
                            .addArtist(
                                SimplifiedArtistObject.builder()
                                    .id("id")
                                    .externalUrls(
                                        ExternalUrlObject.builder().spotify("spotify").build()
                                    )
                                    .href("href")
                                    .name("name")
                                    .type(SimplifiedArtistObject.Type.ARTIST)
                                    .uri("uri")
                                    .build()
                            )
                            .availableMarkets(listOf("CA", "BR", "IT"))
                            .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                            .href("href")
                            .addImage(
                                ImageObject.builder()
                                    .height(300L)
                                    .url(
                                        "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                    )
                                    .width(300L)
                                    .build()
                            )
                            .name("name")
                            .releaseDate("1981-12")
                            .releaseDatePrecision(TrackObject.Album.ReleaseDatePrecision.YEAR)
                            .totalTracks(9L)
                            .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                            .restrictions(
                                AlbumRestrictionObject.builder()
                                    .reason(AlbumRestrictionObject.Reason.MARKET)
                                    .build()
                            )
                            .build()
                    )
                    .addArtist(
                        SimplifiedArtistObject.builder()
                            .id("id")
                            .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                            .href("href")
                            .name("name")
                            .type(SimplifiedArtistObject.Type.ARTIST)
                            .uri("uri")
                            .build()
                    )
                    .addAvailableMarket("string")
                    .discNumber(0L)
                    .durationMs(0L)
                    .explicit(true)
                    .externalIds(
                        ExternalIdObject.builder().ean("ean").isrc("isrc").upc("upc").build()
                    )
                    .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                    .href("href")
                    .isLocal(true)
                    .isPlayable(true)
                    .linkedFrom(
                        LinkedTrackObject.builder()
                            .id("id")
                            .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                            .href("href")
                            .type("type")
                            .uri("uri")
                            .build()
                    )
                    .name("name")
                    .popularity(0L)
                    .previewUrl("preview_url")
                    .restrictions(TrackRestrictionObject.builder().reason("reason").build())
                    .trackNumber(0L)
                    .type(TrackObject.Type.TRACK)
                    .uri("uri")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val recommendationGetResponse =
            RecommendationGetResponse.builder()
                .addSeed(
                    RecommendationGetResponse.Seed.builder()
                        .id("id")
                        .afterFilteringSize(0L)
                        .afterRelinkingSize(0L)
                        .href("href")
                        .initialPoolSize(0L)
                        .type("type")
                        .build()
                )
                .addTrack(
                    TrackObject.builder()
                        .id("id")
                        .album(
                            TrackObject.Album.builder()
                                .id("2up3OPMp9Tb4dAKM2erWXQ")
                                .albumType(TrackObject.Album.AlbumType.COMPILATION)
                                .addArtist(
                                    SimplifiedArtistObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .name("name")
                                        .type(SimplifiedArtistObject.Type.ARTIST)
                                        .uri("uri")
                                        .build()
                                )
                                .availableMarkets(listOf("CA", "BR", "IT"))
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .addImage(
                                    ImageObject.builder()
                                        .height(300L)
                                        .url(
                                            "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                        )
                                        .width(300L)
                                        .build()
                                )
                                .name("name")
                                .releaseDate("1981-12")
                                .releaseDatePrecision(TrackObject.Album.ReleaseDatePrecision.YEAR)
                                .totalTracks(9L)
                                .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                                .restrictions(
                                    AlbumRestrictionObject.builder()
                                        .reason(AlbumRestrictionObject.Reason.MARKET)
                                        .build()
                                )
                                .build()
                        )
                        .addArtist(
                            SimplifiedArtistObject.builder()
                                .id("id")
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .name("name")
                                .type(SimplifiedArtistObject.Type.ARTIST)
                                .uri("uri")
                                .build()
                        )
                        .addAvailableMarket("string")
                        .discNumber(0L)
                        .durationMs(0L)
                        .explicit(true)
                        .externalIds(
                            ExternalIdObject.builder().ean("ean").isrc("isrc").upc("upc").build()
                        )
                        .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                        .href("href")
                        .isLocal(true)
                        .isPlayable(true)
                        .linkedFrom(
                            LinkedTrackObject.builder()
                                .id("id")
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .type("type")
                                .uri("uri")
                                .build()
                        )
                        .name("name")
                        .popularity(0L)
                        .previewUrl("preview_url")
                        .restrictions(TrackRestrictionObject.builder().reason("reason").build())
                        .trackNumber(0L)
                        .type(TrackObject.Type.TRACK)
                        .uri("uri")
                        .build()
                )
                .build()

        val roundtrippedRecommendationGetResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(recommendationGetResponse),
                jacksonTypeRef<RecommendationGetResponse>(),
            )

        assertThat(roundtrippedRecommendationGetResponse).isEqualTo(recommendationGetResponse)
    }
}
