// File generated from our OpenAPI spec by Stainless.

package dev.cjav.spotted.models.recommendations

import dev.cjav.spotted.core.http.QueryParams
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class RecommendationGetParamsTest {

    @Test
    fun create() {
        RecommendationGetParams.builder()
            .limit(10L)
            .market("ES")
            .maxAcousticness(0.0)
            .maxDanceability(0.0)
            .maxDurationMs(0L)
            .maxEnergy(0.0)
            .maxInstrumentalness(0.0)
            .maxKey(0L)
            .maxLiveness(0.0)
            .maxLoudness(0.0)
            .maxMode(0L)
            .maxPopularity(0L)
            .maxSpeechiness(0.0)
            .maxTempo(0.0)
            .maxTimeSignature(0L)
            .maxValence(0.0)
            .minAcousticness(0.0)
            .minDanceability(0.0)
            .minDurationMs(0L)
            .minEnergy(0.0)
            .minInstrumentalness(0.0)
            .minKey(0L)
            .minLiveness(0.0)
            .minLoudness(0.0)
            .minMode(0L)
            .minPopularity(0L)
            .minSpeechiness(0.0)
            .minTempo(0.0)
            .minTimeSignature(11L)
            .minValence(0.0)
            .seedArtists("4NHQUGzhtTLFvgF5SZesLK")
            .seedGenres("classical,country")
            .seedTracks("0c6xIDDpzE81m2q797ordA")
            .targetAcousticness(0.0)
            .targetDanceability(0.0)
            .targetDurationMs(0L)
            .targetEnergy(0.0)
            .targetInstrumentalness(0.0)
            .targetKey(0L)
            .targetLiveness(0.0)
            .targetLoudness(0.0)
            .targetMode(0L)
            .targetPopularity(0L)
            .targetSpeechiness(0.0)
            .targetTempo(0.0)
            .targetTimeSignature(0L)
            .targetValence(0.0)
            .build()
    }

    @Test
    fun queryParams() {
        val params =
            RecommendationGetParams.builder()
                .limit(10L)
                .market("ES")
                .maxAcousticness(0.0)
                .maxDanceability(0.0)
                .maxDurationMs(0L)
                .maxEnergy(0.0)
                .maxInstrumentalness(0.0)
                .maxKey(0L)
                .maxLiveness(0.0)
                .maxLoudness(0.0)
                .maxMode(0L)
                .maxPopularity(0L)
                .maxSpeechiness(0.0)
                .maxTempo(0.0)
                .maxTimeSignature(0L)
                .maxValence(0.0)
                .minAcousticness(0.0)
                .minDanceability(0.0)
                .minDurationMs(0L)
                .minEnergy(0.0)
                .minInstrumentalness(0.0)
                .minKey(0L)
                .minLiveness(0.0)
                .minLoudness(0.0)
                .minMode(0L)
                .minPopularity(0L)
                .minSpeechiness(0.0)
                .minTempo(0.0)
                .minTimeSignature(11L)
                .minValence(0.0)
                .seedArtists("4NHQUGzhtTLFvgF5SZesLK")
                .seedGenres("classical,country")
                .seedTracks("0c6xIDDpzE81m2q797ordA")
                .targetAcousticness(0.0)
                .targetDanceability(0.0)
                .targetDurationMs(0L)
                .targetEnergy(0.0)
                .targetInstrumentalness(0.0)
                .targetKey(0L)
                .targetLiveness(0.0)
                .targetLoudness(0.0)
                .targetMode(0L)
                .targetPopularity(0L)
                .targetSpeechiness(0.0)
                .targetTempo(0.0)
                .targetTimeSignature(0L)
                .targetValence(0.0)
                .build()

        val queryParams = params._queryParams()

        assertThat(queryParams)
            .isEqualTo(
                QueryParams.builder()
                    .put("limit", "10")
                    .put("market", "ES")
                    .put("max_acousticness", "0.0")
                    .put("max_danceability", "0.0")
                    .put("max_duration_ms", "0")
                    .put("max_energy", "0.0")
                    .put("max_instrumentalness", "0.0")
                    .put("max_key", "0")
                    .put("max_liveness", "0.0")
                    .put("max_loudness", "0.0")
                    .put("max_mode", "0")
                    .put("max_popularity", "0")
                    .put("max_speechiness", "0.0")
                    .put("max_tempo", "0.0")
                    .put("max_time_signature", "0")
                    .put("max_valence", "0.0")
                    .put("min_acousticness", "0.0")
                    .put("min_danceability", "0.0")
                    .put("min_duration_ms", "0")
                    .put("min_energy", "0.0")
                    .put("min_instrumentalness", "0.0")
                    .put("min_key", "0")
                    .put("min_liveness", "0.0")
                    .put("min_loudness", "0.0")
                    .put("min_mode", "0")
                    .put("min_popularity", "0")
                    .put("min_speechiness", "0.0")
                    .put("min_tempo", "0.0")
                    .put("min_time_signature", "11")
                    .put("min_valence", "0.0")
                    .put("seed_artists", "4NHQUGzhtTLFvgF5SZesLK")
                    .put("seed_genres", "classical,country")
                    .put("seed_tracks", "0c6xIDDpzE81m2q797ordA")
                    .put("target_acousticness", "0.0")
                    .put("target_danceability", "0.0")
                    .put("target_duration_ms", "0")
                    .put("target_energy", "0.0")
                    .put("target_instrumentalness", "0.0")
                    .put("target_key", "0")
                    .put("target_liveness", "0.0")
                    .put("target_loudness", "0.0")
                    .put("target_mode", "0")
                    .put("target_popularity", "0")
                    .put("target_speechiness", "0.0")
                    .put("target_tempo", "0.0")
                    .put("target_time_signature", "0")
                    .put("target_valence", "0.0")
                    .build()
            )
    }

    @Test
    fun queryParamsWithoutOptionalFields() {
        val params = RecommendationGetParams.builder().build()

        val queryParams = params._queryParams()

        assertThat(queryParams).isEqualTo(QueryParams.builder().build())
    }
}
