// File generated from our OpenAPI spec by Stainless.

package dev.cjav.spotted.models.playlists.tracks

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import dev.cjav.spotted.core.jsonMapper
import dev.cjav.spotted.models.AlbumRestrictionObject
import dev.cjav.spotted.models.ExternalIdObject
import dev.cjav.spotted.models.ExternalUrlObject
import dev.cjav.spotted.models.ImageObject
import dev.cjav.spotted.models.LinkedTrackObject
import dev.cjav.spotted.models.PlaylistTrackObject
import dev.cjav.spotted.models.PlaylistUserObject
import dev.cjav.spotted.models.SimplifiedArtistObject
import dev.cjav.spotted.models.TrackObject
import dev.cjav.spotted.models.TrackRestrictionObject
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TrackListPageResponseTest {

    @Test
    fun create() {
        val trackListPageResponse =
            TrackListPageResponse.builder()
                .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                .limit(20L)
                .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                .offset(0L)
                .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                .total(4L)
                .addItem(
                    PlaylistTrackObject.builder()
                        .addedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addedBy(
                            PlaylistUserObject.builder()
                                .id("id")
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .type(PlaylistUserObject.Type.USER)
                                .uri("uri")
                                .build()
                        )
                        .isLocal(true)
                        .track(
                            TrackObject.builder()
                                .id("id")
                                .album(
                                    TrackObject.Album.builder()
                                        .id("2up3OPMp9Tb4dAKM2erWXQ")
                                        .albumType(TrackObject.Album.AlbumType.COMPILATION)
                                        .addArtist(
                                            SimplifiedArtistObject.builder()
                                                .id("id")
                                                .externalUrls(
                                                    ExternalUrlObject.builder()
                                                        .spotify("spotify")
                                                        .build()
                                                )
                                                .href("href")
                                                .name("name")
                                                .type(SimplifiedArtistObject.Type.ARTIST)
                                                .uri("uri")
                                                .build()
                                        )
                                        .availableMarkets(listOf("CA", "BR", "IT"))
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .addImage(
                                            ImageObject.builder()
                                                .height(300L)
                                                .url(
                                                    "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                                )
                                                .width(300L)
                                                .build()
                                        )
                                        .name("name")
                                        .releaseDate("1981-12")
                                        .releaseDatePrecision(
                                            TrackObject.Album.ReleaseDatePrecision.YEAR
                                        )
                                        .totalTracks(9L)
                                        .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                                        .restrictions(
                                            AlbumRestrictionObject.builder()
                                                .reason(AlbumRestrictionObject.Reason.MARKET)
                                                .build()
                                        )
                                        .build()
                                )
                                .addArtist(
                                    SimplifiedArtistObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .name("name")
                                        .type(SimplifiedArtistObject.Type.ARTIST)
                                        .uri("uri")
                                        .build()
                                )
                                .addAvailableMarket("string")
                                .discNumber(0L)
                                .durationMs(0L)
                                .explicit(true)
                                .externalIds(
                                    ExternalIdObject.builder()
                                        .ean("ean")
                                        .isrc("isrc")
                                        .upc("upc")
                                        .build()
                                )
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .isLocal(true)
                                .isPlayable(true)
                                .linkedFrom(
                                    LinkedTrackObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .type("type")
                                        .uri("uri")
                                        .build()
                                )
                                .name("name")
                                .popularity(0L)
                                .previewUrl("preview_url")
                                .restrictions(
                                    TrackRestrictionObject.builder().reason("reason").build()
                                )
                                .trackNumber(0L)
                                .type(TrackObject.Type.TRACK)
                                .uri("uri")
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(trackListPageResponse.href())
            .isEqualTo("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
        assertThat(trackListPageResponse.limit()).isEqualTo(20L)
        assertThat(trackListPageResponse.next())
            .isEqualTo("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
        assertThat(trackListPageResponse.offset()).isEqualTo(0L)
        assertThat(trackListPageResponse.previous())
            .isEqualTo("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
        assertThat(trackListPageResponse.total()).isEqualTo(4L)
        assertThat(trackListPageResponse.items())
            .containsExactly(
                PlaylistTrackObject.builder()
                    .addedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .addedBy(
                        PlaylistUserObject.builder()
                            .id("id")
                            .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                            .href("href")
                            .type(PlaylistUserObject.Type.USER)
                            .uri("uri")
                            .build()
                    )
                    .isLocal(true)
                    .track(
                        TrackObject.builder()
                            .id("id")
                            .album(
                                TrackObject.Album.builder()
                                    .id("2up3OPMp9Tb4dAKM2erWXQ")
                                    .albumType(TrackObject.Album.AlbumType.COMPILATION)
                                    .addArtist(
                                        SimplifiedArtistObject.builder()
                                            .id("id")
                                            .externalUrls(
                                                ExternalUrlObject.builder()
                                                    .spotify("spotify")
                                                    .build()
                                            )
                                            .href("href")
                                            .name("name")
                                            .type(SimplifiedArtistObject.Type.ARTIST)
                                            .uri("uri")
                                            .build()
                                    )
                                    .availableMarkets(listOf("CA", "BR", "IT"))
                                    .externalUrls(
                                        ExternalUrlObject.builder().spotify("spotify").build()
                                    )
                                    .href("href")
                                    .addImage(
                                        ImageObject.builder()
                                            .height(300L)
                                            .url(
                                                "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                            )
                                            .width(300L)
                                            .build()
                                    )
                                    .name("name")
                                    .releaseDate("1981-12")
                                    .releaseDatePrecision(
                                        TrackObject.Album.ReleaseDatePrecision.YEAR
                                    )
                                    .totalTracks(9L)
                                    .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                                    .restrictions(
                                        AlbumRestrictionObject.builder()
                                            .reason(AlbumRestrictionObject.Reason.MARKET)
                                            .build()
                                    )
                                    .build()
                            )
                            .addArtist(
                                SimplifiedArtistObject.builder()
                                    .id("id")
                                    .externalUrls(
                                        ExternalUrlObject.builder().spotify("spotify").build()
                                    )
                                    .href("href")
                                    .name("name")
                                    .type(SimplifiedArtistObject.Type.ARTIST)
                                    .uri("uri")
                                    .build()
                            )
                            .addAvailableMarket("string")
                            .discNumber(0L)
                            .durationMs(0L)
                            .explicit(true)
                            .externalIds(
                                ExternalIdObject.builder()
                                    .ean("ean")
                                    .isrc("isrc")
                                    .upc("upc")
                                    .build()
                            )
                            .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                            .href("href")
                            .isLocal(true)
                            .isPlayable(true)
                            .linkedFrom(
                                LinkedTrackObject.builder()
                                    .id("id")
                                    .externalUrls(
                                        ExternalUrlObject.builder().spotify("spotify").build()
                                    )
                                    .href("href")
                                    .type("type")
                                    .uri("uri")
                                    .build()
                            )
                            .name("name")
                            .popularity(0L)
                            .previewUrl("preview_url")
                            .restrictions(TrackRestrictionObject.builder().reason("reason").build())
                            .trackNumber(0L)
                            .type(TrackObject.Type.TRACK)
                            .uri("uri")
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val trackListPageResponse =
            TrackListPageResponse.builder()
                .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                .limit(20L)
                .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                .offset(0L)
                .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                .total(4L)
                .addItem(
                    PlaylistTrackObject.builder()
                        .addedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addedBy(
                            PlaylistUserObject.builder()
                                .id("id")
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .type(PlaylistUserObject.Type.USER)
                                .uri("uri")
                                .build()
                        )
                        .isLocal(true)
                        .track(
                            TrackObject.builder()
                                .id("id")
                                .album(
                                    TrackObject.Album.builder()
                                        .id("2up3OPMp9Tb4dAKM2erWXQ")
                                        .albumType(TrackObject.Album.AlbumType.COMPILATION)
                                        .addArtist(
                                            SimplifiedArtistObject.builder()
                                                .id("id")
                                                .externalUrls(
                                                    ExternalUrlObject.builder()
                                                        .spotify("spotify")
                                                        .build()
                                                )
                                                .href("href")
                                                .name("name")
                                                .type(SimplifiedArtistObject.Type.ARTIST)
                                                .uri("uri")
                                                .build()
                                        )
                                        .availableMarkets(listOf("CA", "BR", "IT"))
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .addImage(
                                            ImageObject.builder()
                                                .height(300L)
                                                .url(
                                                    "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                                )
                                                .width(300L)
                                                .build()
                                        )
                                        .name("name")
                                        .releaseDate("1981-12")
                                        .releaseDatePrecision(
                                            TrackObject.Album.ReleaseDatePrecision.YEAR
                                        )
                                        .totalTracks(9L)
                                        .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                                        .restrictions(
                                            AlbumRestrictionObject.builder()
                                                .reason(AlbumRestrictionObject.Reason.MARKET)
                                                .build()
                                        )
                                        .build()
                                )
                                .addArtist(
                                    SimplifiedArtistObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .name("name")
                                        .type(SimplifiedArtistObject.Type.ARTIST)
                                        .uri("uri")
                                        .build()
                                )
                                .addAvailableMarket("string")
                                .discNumber(0L)
                                .durationMs(0L)
                                .explicit(true)
                                .externalIds(
                                    ExternalIdObject.builder()
                                        .ean("ean")
                                        .isrc("isrc")
                                        .upc("upc")
                                        .build()
                                )
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .isLocal(true)
                                .isPlayable(true)
                                .linkedFrom(
                                    LinkedTrackObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .type("type")
                                        .uri("uri")
                                        .build()
                                )
                                .name("name")
                                .popularity(0L)
                                .previewUrl("preview_url")
                                .restrictions(
                                    TrackRestrictionObject.builder().reason("reason").build()
                                )
                                .trackNumber(0L)
                                .type(TrackObject.Type.TRACK)
                                .uri("uri")
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedTrackListPageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(trackListPageResponse),
                jacksonTypeRef<TrackListPageResponse>(),
            )

        assertThat(roundtrippedTrackListPageResponse).isEqualTo(trackListPageResponse)
    }
}
