// File generated from our OpenAPI spec by Stainless.

package com.spotted.api.models.search

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.spotted.api.core.jsonMapper
import com.spotted.api.models.AlbumRestrictionObject
import com.spotted.api.models.ArtistObject
import com.spotted.api.models.AudiobookBase
import com.spotted.api.models.AuthorObject
import com.spotted.api.models.CopyrightObject
import com.spotted.api.models.EpisodeRestrictionObject
import com.spotted.api.models.ExternalIdObject
import com.spotted.api.models.ExternalUrlObject
import com.spotted.api.models.FollowersObject
import com.spotted.api.models.ImageObject
import com.spotted.api.models.LinkedTrackObject
import com.spotted.api.models.NarratorObject
import com.spotted.api.models.PagingPlaylistObject
import com.spotted.api.models.PlaylistTracksRefObject
import com.spotted.api.models.PlaylistUserObject
import com.spotted.api.models.ResumePointObject
import com.spotted.api.models.ShowBase
import com.spotted.api.models.SimplifiedArtistObject
import com.spotted.api.models.SimplifiedEpisodeObject
import com.spotted.api.models.SimplifiedPlaylistObject
import com.spotted.api.models.TrackObject
import com.spotted.api.models.TrackRestrictionObject
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SearchQueryResponseTest {

    @Test
    fun create() {
        val searchQueryResponse =
            SearchQueryResponse.builder()
                .albums(
                    SearchQueryResponse.Albums.builder()
                        .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                        .limit(20L)
                        .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .offset(0L)
                        .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .total(4L)
                        .addItem(
                            SearchQueryResponse.Albums.Item.builder()
                                .id("2up3OPMp9Tb4dAKM2erWXQ")
                                .albumType(SearchQueryResponse.Albums.Item.AlbumType.COMPILATION)
                                .addArtist(
                                    SimplifiedArtistObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .name("name")
                                        .type(SimplifiedArtistObject.Type.ARTIST)
                                        .uri("uri")
                                        .build()
                                )
                                .availableMarkets(listOf("CA", "BR", "IT"))
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .addImage(
                                    ImageObject.builder()
                                        .height(300L)
                                        .url(
                                            "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                        )
                                        .width(300L)
                                        .build()
                                )
                                .name("name")
                                .releaseDate("1981-12")
                                .releaseDatePrecision(
                                    SearchQueryResponse.Albums.Item.ReleaseDatePrecision.YEAR
                                )
                                .totalTracks(9L)
                                .type(SearchQueryResponse.Albums.Item.Type.ALBUM)
                                .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                                .restrictions(
                                    AlbumRestrictionObject.builder()
                                        .reason(AlbumRestrictionObject.Reason.MARKET)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .artists(
                    SearchQueryResponse.Artists.builder()
                        .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                        .limit(20L)
                        .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .offset(0L)
                        .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .total(4L)
                        .addItem(
                            ArtistObject.builder()
                                .id("id")
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .followers(FollowersObject.builder().href("href").total(0L).build())
                                .addGenre("Prog rock")
                                .addGenre("Grunge")
                                .href("href")
                                .addImage(
                                    ImageObject.builder()
                                        .height(300L)
                                        .url(
                                            "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                        )
                                        .width(300L)
                                        .build()
                                )
                                .name("name")
                                .popularity(0L)
                                .type(ArtistObject.Type.ARTIST)
                                .uri("uri")
                                .build()
                        )
                        .build()
                )
                .audiobooks(
                    SearchQueryResponse.Audiobooks.builder()
                        .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                        .limit(20L)
                        .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .offset(0L)
                        .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .total(4L)
                        .addItem(
                            AudiobookBase.builder()
                                .id("id")
                                .addAuthor(AuthorObject.builder().name("name").build())
                                .addAvailableMarket("string")
                                .addCopyright(
                                    CopyrightObject.builder().text("text").type("type").build()
                                )
                                .description("description")
                                .explicit(true)
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .htmlDescription("html_description")
                                .addImage(
                                    ImageObject.builder()
                                        .height(300L)
                                        .url(
                                            "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                        )
                                        .width(300L)
                                        .build()
                                )
                                .addLanguage("string")
                                .mediaType("media_type")
                                .name("name")
                                .addNarrator(NarratorObject.builder().name("name").build())
                                .publisher("publisher")
                                .totalChapters(0L)
                                .type(AudiobookBase.Type.AUDIOBOOK)
                                .uri("uri")
                                .edition("Unabridged")
                                .build()
                        )
                        .build()
                )
                .episodes(
                    SearchQueryResponse.Episodes.builder()
                        .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                        .limit(20L)
                        .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .offset(0L)
                        .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .total(4L)
                        .addItem(
                            SimplifiedEpisodeObject.builder()
                                .id("5Xt5DXGzch68nYYamXrNxZ")
                                .audioPreviewUrl(
                                    "https://p.scdn.co/mp3-preview/2f37da1d4221f40b9d1a98cd191f4d6f1646ad17"
                                )
                                .description(
                                    "A Spotify podcast sharing fresh insights on important topics of the moment—in a way only Spotify can. You’ll hear from experts in the music, podcast and tech industries as we discover and uncover stories about our work and the world around us.\n"
                                )
                                .durationMs(1686230L)
                                .explicit(true)
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("https://api.spotify.com/v1/episodes/5Xt5DXGzch68nYYamXrNxZ")
                                .htmlDescription(
                                    "<p>A Spotify podcast sharing fresh insights on important topics of the moment—in a way only Spotify can. You’ll hear from experts in the music, podcast and tech industries as we discover and uncover stories about our work and the world around us.</p>\n"
                                )
                                .addImage(
                                    ImageObject.builder()
                                        .height(300L)
                                        .url(
                                            "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                        )
                                        .width(300L)
                                        .build()
                                )
                                .isExternallyHosted(true)
                                .isPlayable(true)
                                .addLanguage("fr")
                                .addLanguage("en")
                                .name(
                                    "Starting Your Own Podcast: Tips, Tricks, and Advice From Anchor Creators\n"
                                )
                                .releaseDate("1981-12-15")
                                .releaseDatePrecision(
                                    SimplifiedEpisodeObject.ReleaseDatePrecision.DAY
                                )
                                .type(SimplifiedEpisodeObject.Type.EPISODE)
                                .uri("spotify:episode:0zLhl3WsOCQHbe1BPTiHgr")
                                .language("en")
                                .restrictions(
                                    EpisodeRestrictionObject.builder().reason("reason").build()
                                )
                                .resumePoint(
                                    ResumePointObject.builder()
                                        .fullyPlayed(true)
                                        .resumePositionMs(0L)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .playlists(
                    PagingPlaylistObject.builder()
                        .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                        .limit(20L)
                        .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .offset(0L)
                        .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .total(4L)
                        .addItem(
                            SimplifiedPlaylistObject.builder()
                                .id("id")
                                .collaborative(true)
                                .description("description")
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .addImage(
                                    ImageObject.builder()
                                        .height(300L)
                                        .url(
                                            "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                        )
                                        .width(300L)
                                        .build()
                                )
                                .name("name")
                                .owner(
                                    SimplifiedPlaylistObject.Owner.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .type(PlaylistUserObject.Type.USER)
                                        .uri("uri")
                                        .displayName("display_name")
                                        .build()
                                )
                                .public_(true)
                                .snapshotId("snapshot_id")
                                .tracks(
                                    PlaylistTracksRefObject.builder().href("href").total(0L).build()
                                )
                                .type("type")
                                .uri("uri")
                                .build()
                        )
                        .build()
                )
                .shows(
                    SearchQueryResponse.Shows.builder()
                        .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                        .limit(20L)
                        .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .offset(0L)
                        .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .total(4L)
                        .addItem(
                            ShowBase.builder()
                                .id("id")
                                .addAvailableMarket("string")
                                .addCopyright(
                                    CopyrightObject.builder().text("text").type("type").build()
                                )
                                .description("description")
                                .explicit(true)
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .htmlDescription("html_description")
                                .addImage(
                                    ImageObject.builder()
                                        .height(300L)
                                        .url(
                                            "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                        )
                                        .width(300L)
                                        .build()
                                )
                                .isExternallyHosted(true)
                                .addLanguage("string")
                                .mediaType("media_type")
                                .name("name")
                                .publisher("publisher")
                                .totalEpisodes(0L)
                                .type(ShowBase.Type.SHOW)
                                .uri("uri")
                                .build()
                        )
                        .build()
                )
                .tracks(
                    SearchQueryResponse.Tracks.builder()
                        .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                        .limit(20L)
                        .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .offset(0L)
                        .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .total(4L)
                        .addItem(
                            TrackObject.builder()
                                .id("id")
                                .album(
                                    TrackObject.Album.builder()
                                        .id("2up3OPMp9Tb4dAKM2erWXQ")
                                        .albumType(TrackObject.Album.AlbumType.COMPILATION)
                                        .addArtist(
                                            SimplifiedArtistObject.builder()
                                                .id("id")
                                                .externalUrls(
                                                    ExternalUrlObject.builder()
                                                        .spotify("spotify")
                                                        .build()
                                                )
                                                .href("href")
                                                .name("name")
                                                .type(SimplifiedArtistObject.Type.ARTIST)
                                                .uri("uri")
                                                .build()
                                        )
                                        .availableMarkets(listOf("CA", "BR", "IT"))
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .addImage(
                                            ImageObject.builder()
                                                .height(300L)
                                                .url(
                                                    "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                                )
                                                .width(300L)
                                                .build()
                                        )
                                        .name("name")
                                        .releaseDate("1981-12")
                                        .releaseDatePrecision(
                                            TrackObject.Album.ReleaseDatePrecision.YEAR
                                        )
                                        .totalTracks(9L)
                                        .type(TrackObject.Album.Type.ALBUM)
                                        .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                                        .restrictions(
                                            AlbumRestrictionObject.builder()
                                                .reason(AlbumRestrictionObject.Reason.MARKET)
                                                .build()
                                        )
                                        .build()
                                )
                                .addArtist(
                                    SimplifiedArtistObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .name("name")
                                        .type(SimplifiedArtistObject.Type.ARTIST)
                                        .uri("uri")
                                        .build()
                                )
                                .addAvailableMarket("string")
                                .discNumber(0L)
                                .durationMs(0L)
                                .explicit(true)
                                .externalIds(
                                    ExternalIdObject.builder()
                                        .ean("ean")
                                        .isrc("isrc")
                                        .upc("upc")
                                        .build()
                                )
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .isLocal(true)
                                .isPlayable(true)
                                .linkedFrom(
                                    LinkedTrackObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .type("type")
                                        .uri("uri")
                                        .build()
                                )
                                .name("name")
                                .popularity(0L)
                                .previewUrl("preview_url")
                                .restrictions(
                                    TrackRestrictionObject.builder().reason("reason").build()
                                )
                                .trackNumber(0L)
                                .type(TrackObject.Type.TRACK)
                                .uri("uri")
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(searchQueryResponse.albums())
            .isEqualTo(
                SearchQueryResponse.Albums.builder()
                    .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                    .limit(20L)
                    .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                    .offset(0L)
                    .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                    .total(4L)
                    .addItem(
                        SearchQueryResponse.Albums.Item.builder()
                            .id("2up3OPMp9Tb4dAKM2erWXQ")
                            .albumType(SearchQueryResponse.Albums.Item.AlbumType.COMPILATION)
                            .addArtist(
                                SimplifiedArtistObject.builder()
                                    .id("id")
                                    .externalUrls(
                                        ExternalUrlObject.builder().spotify("spotify").build()
                                    )
                                    .href("href")
                                    .name("name")
                                    .type(SimplifiedArtistObject.Type.ARTIST)
                                    .uri("uri")
                                    .build()
                            )
                            .availableMarkets(listOf("CA", "BR", "IT"))
                            .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                            .href("href")
                            .addImage(
                                ImageObject.builder()
                                    .height(300L)
                                    .url(
                                        "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                    )
                                    .width(300L)
                                    .build()
                            )
                            .name("name")
                            .releaseDate("1981-12")
                            .releaseDatePrecision(
                                SearchQueryResponse.Albums.Item.ReleaseDatePrecision.YEAR
                            )
                            .totalTracks(9L)
                            .type(SearchQueryResponse.Albums.Item.Type.ALBUM)
                            .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                            .restrictions(
                                AlbumRestrictionObject.builder()
                                    .reason(AlbumRestrictionObject.Reason.MARKET)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(searchQueryResponse.artists())
            .isEqualTo(
                SearchQueryResponse.Artists.builder()
                    .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                    .limit(20L)
                    .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                    .offset(0L)
                    .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                    .total(4L)
                    .addItem(
                        ArtistObject.builder()
                            .id("id")
                            .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                            .followers(FollowersObject.builder().href("href").total(0L).build())
                            .addGenre("Prog rock")
                            .addGenre("Grunge")
                            .href("href")
                            .addImage(
                                ImageObject.builder()
                                    .height(300L)
                                    .url(
                                        "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                    )
                                    .width(300L)
                                    .build()
                            )
                            .name("name")
                            .popularity(0L)
                            .type(ArtistObject.Type.ARTIST)
                            .uri("uri")
                            .build()
                    )
                    .build()
            )
        assertThat(searchQueryResponse.audiobooks())
            .isEqualTo(
                SearchQueryResponse.Audiobooks.builder()
                    .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                    .limit(20L)
                    .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                    .offset(0L)
                    .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                    .total(4L)
                    .addItem(
                        AudiobookBase.builder()
                            .id("id")
                            .addAuthor(AuthorObject.builder().name("name").build())
                            .addAvailableMarket("string")
                            .addCopyright(
                                CopyrightObject.builder().text("text").type("type").build()
                            )
                            .description("description")
                            .explicit(true)
                            .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                            .href("href")
                            .htmlDescription("html_description")
                            .addImage(
                                ImageObject.builder()
                                    .height(300L)
                                    .url(
                                        "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                    )
                                    .width(300L)
                                    .build()
                            )
                            .addLanguage("string")
                            .mediaType("media_type")
                            .name("name")
                            .addNarrator(NarratorObject.builder().name("name").build())
                            .publisher("publisher")
                            .totalChapters(0L)
                            .type(AudiobookBase.Type.AUDIOBOOK)
                            .uri("uri")
                            .edition("Unabridged")
                            .build()
                    )
                    .build()
            )
        assertThat(searchQueryResponse.episodes())
            .isEqualTo(
                SearchQueryResponse.Episodes.builder()
                    .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                    .limit(20L)
                    .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                    .offset(0L)
                    .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                    .total(4L)
                    .addItem(
                        SimplifiedEpisodeObject.builder()
                            .id("5Xt5DXGzch68nYYamXrNxZ")
                            .audioPreviewUrl(
                                "https://p.scdn.co/mp3-preview/2f37da1d4221f40b9d1a98cd191f4d6f1646ad17"
                            )
                            .description(
                                "A Spotify podcast sharing fresh insights on important topics of the moment—in a way only Spotify can. You’ll hear from experts in the music, podcast and tech industries as we discover and uncover stories about our work and the world around us.\n"
                            )
                            .durationMs(1686230L)
                            .explicit(true)
                            .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                            .href("https://api.spotify.com/v1/episodes/5Xt5DXGzch68nYYamXrNxZ")
                            .htmlDescription(
                                "<p>A Spotify podcast sharing fresh insights on important topics of the moment—in a way only Spotify can. You’ll hear from experts in the music, podcast and tech industries as we discover and uncover stories about our work and the world around us.</p>\n"
                            )
                            .addImage(
                                ImageObject.builder()
                                    .height(300L)
                                    .url(
                                        "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                    )
                                    .width(300L)
                                    .build()
                            )
                            .isExternallyHosted(true)
                            .isPlayable(true)
                            .addLanguage("fr")
                            .addLanguage("en")
                            .name(
                                "Starting Your Own Podcast: Tips, Tricks, and Advice From Anchor Creators\n"
                            )
                            .releaseDate("1981-12-15")
                            .releaseDatePrecision(SimplifiedEpisodeObject.ReleaseDatePrecision.DAY)
                            .type(SimplifiedEpisodeObject.Type.EPISODE)
                            .uri("spotify:episode:0zLhl3WsOCQHbe1BPTiHgr")
                            .language("en")
                            .restrictions(
                                EpisodeRestrictionObject.builder().reason("reason").build()
                            )
                            .resumePoint(
                                ResumePointObject.builder()
                                    .fullyPlayed(true)
                                    .resumePositionMs(0L)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(searchQueryResponse.playlists())
            .isEqualTo(
                PagingPlaylistObject.builder()
                    .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                    .limit(20L)
                    .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                    .offset(0L)
                    .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                    .total(4L)
                    .addItem(
                        SimplifiedPlaylistObject.builder()
                            .id("id")
                            .collaborative(true)
                            .description("description")
                            .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                            .href("href")
                            .addImage(
                                ImageObject.builder()
                                    .height(300L)
                                    .url(
                                        "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                    )
                                    .width(300L)
                                    .build()
                            )
                            .name("name")
                            .owner(
                                SimplifiedPlaylistObject.Owner.builder()
                                    .id("id")
                                    .externalUrls(
                                        ExternalUrlObject.builder().spotify("spotify").build()
                                    )
                                    .href("href")
                                    .type(PlaylistUserObject.Type.USER)
                                    .uri("uri")
                                    .displayName("display_name")
                                    .build()
                            )
                            .public_(true)
                            .snapshotId("snapshot_id")
                            .tracks(
                                PlaylistTracksRefObject.builder().href("href").total(0L).build()
                            )
                            .type("type")
                            .uri("uri")
                            .build()
                    )
                    .build()
            )
        assertThat(searchQueryResponse.shows())
            .isEqualTo(
                SearchQueryResponse.Shows.builder()
                    .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                    .limit(20L)
                    .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                    .offset(0L)
                    .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                    .total(4L)
                    .addItem(
                        ShowBase.builder()
                            .id("id")
                            .addAvailableMarket("string")
                            .addCopyright(
                                CopyrightObject.builder().text("text").type("type").build()
                            )
                            .description("description")
                            .explicit(true)
                            .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                            .href("href")
                            .htmlDescription("html_description")
                            .addImage(
                                ImageObject.builder()
                                    .height(300L)
                                    .url(
                                        "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                    )
                                    .width(300L)
                                    .build()
                            )
                            .isExternallyHosted(true)
                            .addLanguage("string")
                            .mediaType("media_type")
                            .name("name")
                            .publisher("publisher")
                            .totalEpisodes(0L)
                            .type(ShowBase.Type.SHOW)
                            .uri("uri")
                            .build()
                    )
                    .build()
            )
        assertThat(searchQueryResponse.tracks())
            .isEqualTo(
                SearchQueryResponse.Tracks.builder()
                    .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                    .limit(20L)
                    .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                    .offset(0L)
                    .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                    .total(4L)
                    .addItem(
                        TrackObject.builder()
                            .id("id")
                            .album(
                                TrackObject.Album.builder()
                                    .id("2up3OPMp9Tb4dAKM2erWXQ")
                                    .albumType(TrackObject.Album.AlbumType.COMPILATION)
                                    .addArtist(
                                        SimplifiedArtistObject.builder()
                                            .id("id")
                                            .externalUrls(
                                                ExternalUrlObject.builder()
                                                    .spotify("spotify")
                                                    .build()
                                            )
                                            .href("href")
                                            .name("name")
                                            .type(SimplifiedArtistObject.Type.ARTIST)
                                            .uri("uri")
                                            .build()
                                    )
                                    .availableMarkets(listOf("CA", "BR", "IT"))
                                    .externalUrls(
                                        ExternalUrlObject.builder().spotify("spotify").build()
                                    )
                                    .href("href")
                                    .addImage(
                                        ImageObject.builder()
                                            .height(300L)
                                            .url(
                                                "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                            )
                                            .width(300L)
                                            .build()
                                    )
                                    .name("name")
                                    .releaseDate("1981-12")
                                    .releaseDatePrecision(
                                        TrackObject.Album.ReleaseDatePrecision.YEAR
                                    )
                                    .totalTracks(9L)
                                    .type(TrackObject.Album.Type.ALBUM)
                                    .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                                    .restrictions(
                                        AlbumRestrictionObject.builder()
                                            .reason(AlbumRestrictionObject.Reason.MARKET)
                                            .build()
                                    )
                                    .build()
                            )
                            .addArtist(
                                SimplifiedArtistObject.builder()
                                    .id("id")
                                    .externalUrls(
                                        ExternalUrlObject.builder().spotify("spotify").build()
                                    )
                                    .href("href")
                                    .name("name")
                                    .type(SimplifiedArtistObject.Type.ARTIST)
                                    .uri("uri")
                                    .build()
                            )
                            .addAvailableMarket("string")
                            .discNumber(0L)
                            .durationMs(0L)
                            .explicit(true)
                            .externalIds(
                                ExternalIdObject.builder()
                                    .ean("ean")
                                    .isrc("isrc")
                                    .upc("upc")
                                    .build()
                            )
                            .externalUrls(ExternalUrlObject.builder().spotify("spotify").build())
                            .href("href")
                            .isLocal(true)
                            .isPlayable(true)
                            .linkedFrom(
                                LinkedTrackObject.builder()
                                    .id("id")
                                    .externalUrls(
                                        ExternalUrlObject.builder().spotify("spotify").build()
                                    )
                                    .href("href")
                                    .type("type")
                                    .uri("uri")
                                    .build()
                            )
                            .name("name")
                            .popularity(0L)
                            .previewUrl("preview_url")
                            .restrictions(TrackRestrictionObject.builder().reason("reason").build())
                            .trackNumber(0L)
                            .type(TrackObject.Type.TRACK)
                            .uri("uri")
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val searchQueryResponse =
            SearchQueryResponse.builder()
                .albums(
                    SearchQueryResponse.Albums.builder()
                        .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                        .limit(20L)
                        .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .offset(0L)
                        .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .total(4L)
                        .addItem(
                            SearchQueryResponse.Albums.Item.builder()
                                .id("2up3OPMp9Tb4dAKM2erWXQ")
                                .albumType(SearchQueryResponse.Albums.Item.AlbumType.COMPILATION)
                                .addArtist(
                                    SimplifiedArtistObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .name("name")
                                        .type(SimplifiedArtistObject.Type.ARTIST)
                                        .uri("uri")
                                        .build()
                                )
                                .availableMarkets(listOf("CA", "BR", "IT"))
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .addImage(
                                    ImageObject.builder()
                                        .height(300L)
                                        .url(
                                            "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                        )
                                        .width(300L)
                                        .build()
                                )
                                .name("name")
                                .releaseDate("1981-12")
                                .releaseDatePrecision(
                                    SearchQueryResponse.Albums.Item.ReleaseDatePrecision.YEAR
                                )
                                .totalTracks(9L)
                                .type(SearchQueryResponse.Albums.Item.Type.ALBUM)
                                .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                                .restrictions(
                                    AlbumRestrictionObject.builder()
                                        .reason(AlbumRestrictionObject.Reason.MARKET)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .artists(
                    SearchQueryResponse.Artists.builder()
                        .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                        .limit(20L)
                        .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .offset(0L)
                        .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .total(4L)
                        .addItem(
                            ArtistObject.builder()
                                .id("id")
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .followers(FollowersObject.builder().href("href").total(0L).build())
                                .addGenre("Prog rock")
                                .addGenre("Grunge")
                                .href("href")
                                .addImage(
                                    ImageObject.builder()
                                        .height(300L)
                                        .url(
                                            "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                        )
                                        .width(300L)
                                        .build()
                                )
                                .name("name")
                                .popularity(0L)
                                .type(ArtistObject.Type.ARTIST)
                                .uri("uri")
                                .build()
                        )
                        .build()
                )
                .audiobooks(
                    SearchQueryResponse.Audiobooks.builder()
                        .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                        .limit(20L)
                        .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .offset(0L)
                        .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .total(4L)
                        .addItem(
                            AudiobookBase.builder()
                                .id("id")
                                .addAuthor(AuthorObject.builder().name("name").build())
                                .addAvailableMarket("string")
                                .addCopyright(
                                    CopyrightObject.builder().text("text").type("type").build()
                                )
                                .description("description")
                                .explicit(true)
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .htmlDescription("html_description")
                                .addImage(
                                    ImageObject.builder()
                                        .height(300L)
                                        .url(
                                            "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                        )
                                        .width(300L)
                                        .build()
                                )
                                .addLanguage("string")
                                .mediaType("media_type")
                                .name("name")
                                .addNarrator(NarratorObject.builder().name("name").build())
                                .publisher("publisher")
                                .totalChapters(0L)
                                .type(AudiobookBase.Type.AUDIOBOOK)
                                .uri("uri")
                                .edition("Unabridged")
                                .build()
                        )
                        .build()
                )
                .episodes(
                    SearchQueryResponse.Episodes.builder()
                        .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                        .limit(20L)
                        .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .offset(0L)
                        .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .total(4L)
                        .addItem(
                            SimplifiedEpisodeObject.builder()
                                .id("5Xt5DXGzch68nYYamXrNxZ")
                                .audioPreviewUrl(
                                    "https://p.scdn.co/mp3-preview/2f37da1d4221f40b9d1a98cd191f4d6f1646ad17"
                                )
                                .description(
                                    "A Spotify podcast sharing fresh insights on important topics of the moment—in a way only Spotify can. You’ll hear from experts in the music, podcast and tech industries as we discover and uncover stories about our work and the world around us.\n"
                                )
                                .durationMs(1686230L)
                                .explicit(true)
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("https://api.spotify.com/v1/episodes/5Xt5DXGzch68nYYamXrNxZ")
                                .htmlDescription(
                                    "<p>A Spotify podcast sharing fresh insights on important topics of the moment—in a way only Spotify can. You’ll hear from experts in the music, podcast and tech industries as we discover and uncover stories about our work and the world around us.</p>\n"
                                )
                                .addImage(
                                    ImageObject.builder()
                                        .height(300L)
                                        .url(
                                            "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                        )
                                        .width(300L)
                                        .build()
                                )
                                .isExternallyHosted(true)
                                .isPlayable(true)
                                .addLanguage("fr")
                                .addLanguage("en")
                                .name(
                                    "Starting Your Own Podcast: Tips, Tricks, and Advice From Anchor Creators\n"
                                )
                                .releaseDate("1981-12-15")
                                .releaseDatePrecision(
                                    SimplifiedEpisodeObject.ReleaseDatePrecision.DAY
                                )
                                .type(SimplifiedEpisodeObject.Type.EPISODE)
                                .uri("spotify:episode:0zLhl3WsOCQHbe1BPTiHgr")
                                .language("en")
                                .restrictions(
                                    EpisodeRestrictionObject.builder().reason("reason").build()
                                )
                                .resumePoint(
                                    ResumePointObject.builder()
                                        .fullyPlayed(true)
                                        .resumePositionMs(0L)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .playlists(
                    PagingPlaylistObject.builder()
                        .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                        .limit(20L)
                        .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .offset(0L)
                        .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .total(4L)
                        .addItem(
                            SimplifiedPlaylistObject.builder()
                                .id("id")
                                .collaborative(true)
                                .description("description")
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .addImage(
                                    ImageObject.builder()
                                        .height(300L)
                                        .url(
                                            "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                        )
                                        .width(300L)
                                        .build()
                                )
                                .name("name")
                                .owner(
                                    SimplifiedPlaylistObject.Owner.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .type(PlaylistUserObject.Type.USER)
                                        .uri("uri")
                                        .displayName("display_name")
                                        .build()
                                )
                                .public_(true)
                                .snapshotId("snapshot_id")
                                .tracks(
                                    PlaylistTracksRefObject.builder().href("href").total(0L).build()
                                )
                                .type("type")
                                .uri("uri")
                                .build()
                        )
                        .build()
                )
                .shows(
                    SearchQueryResponse.Shows.builder()
                        .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                        .limit(20L)
                        .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .offset(0L)
                        .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .total(4L)
                        .addItem(
                            ShowBase.builder()
                                .id("id")
                                .addAvailableMarket("string")
                                .addCopyright(
                                    CopyrightObject.builder().text("text").type("type").build()
                                )
                                .description("description")
                                .explicit(true)
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .htmlDescription("html_description")
                                .addImage(
                                    ImageObject.builder()
                                        .height(300L)
                                        .url(
                                            "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                        )
                                        .width(300L)
                                        .build()
                                )
                                .isExternallyHosted(true)
                                .addLanguage("string")
                                .mediaType("media_type")
                                .name("name")
                                .publisher("publisher")
                                .totalEpisodes(0L)
                                .type(ShowBase.Type.SHOW)
                                .uri("uri")
                                .build()
                        )
                        .build()
                )
                .tracks(
                    SearchQueryResponse.Tracks.builder()
                        .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                        .limit(20L)
                        .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .offset(0L)
                        .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                        .total(4L)
                        .addItem(
                            TrackObject.builder()
                                .id("id")
                                .album(
                                    TrackObject.Album.builder()
                                        .id("2up3OPMp9Tb4dAKM2erWXQ")
                                        .albumType(TrackObject.Album.AlbumType.COMPILATION)
                                        .addArtist(
                                            SimplifiedArtistObject.builder()
                                                .id("id")
                                                .externalUrls(
                                                    ExternalUrlObject.builder()
                                                        .spotify("spotify")
                                                        .build()
                                                )
                                                .href("href")
                                                .name("name")
                                                .type(SimplifiedArtistObject.Type.ARTIST)
                                                .uri("uri")
                                                .build()
                                        )
                                        .availableMarkets(listOf("CA", "BR", "IT"))
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .addImage(
                                            ImageObject.builder()
                                                .height(300L)
                                                .url(
                                                    "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                                )
                                                .width(300L)
                                                .build()
                                        )
                                        .name("name")
                                        .releaseDate("1981-12")
                                        .releaseDatePrecision(
                                            TrackObject.Album.ReleaseDatePrecision.YEAR
                                        )
                                        .totalTracks(9L)
                                        .type(TrackObject.Album.Type.ALBUM)
                                        .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                                        .restrictions(
                                            AlbumRestrictionObject.builder()
                                                .reason(AlbumRestrictionObject.Reason.MARKET)
                                                .build()
                                        )
                                        .build()
                                )
                                .addArtist(
                                    SimplifiedArtistObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .name("name")
                                        .type(SimplifiedArtistObject.Type.ARTIST)
                                        .uri("uri")
                                        .build()
                                )
                                .addAvailableMarket("string")
                                .discNumber(0L)
                                .durationMs(0L)
                                .explicit(true)
                                .externalIds(
                                    ExternalIdObject.builder()
                                        .ean("ean")
                                        .isrc("isrc")
                                        .upc("upc")
                                        .build()
                                )
                                .externalUrls(
                                    ExternalUrlObject.builder().spotify("spotify").build()
                                )
                                .href("href")
                                .isLocal(true)
                                .isPlayable(true)
                                .linkedFrom(
                                    LinkedTrackObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder().spotify("spotify").build()
                                        )
                                        .href("href")
                                        .type("type")
                                        .uri("uri")
                                        .build()
                                )
                                .name("name")
                                .popularity(0L)
                                .previewUrl("preview_url")
                                .restrictions(
                                    TrackRestrictionObject.builder().reason("reason").build()
                                )
                                .trackNumber(0L)
                                .type(TrackObject.Type.TRACK)
                                .uri("uri")
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedSearchQueryResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(searchQueryResponse),
                jacksonTypeRef<SearchQueryResponse>(),
            )

        assertThat(roundtrippedSearchQueryResponse).isEqualTo(searchQueryResponse)
    }
}
