// File generated from our OpenAPI spec by Stainless.

package dev.cjav.spotted.models.me.top

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import dev.cjav.spotted.core.jsonMapper
import dev.cjav.spotted.models.AlbumRestrictionObject
import dev.cjav.spotted.models.ExternalIdObject
import dev.cjav.spotted.models.ExternalUrlObject
import dev.cjav.spotted.models.ImageObject
import dev.cjav.spotted.models.LinkedTrackObject
import dev.cjav.spotted.models.SimplifiedArtistObject
import dev.cjav.spotted.models.TrackObject
import dev.cjav.spotted.models.TrackRestrictionObject
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TopListTopTracksPageResponseTest {

    @Test
    fun create() {
        val topListTopTracksPageResponse =
            TopListTopTracksPageResponse.builder()
                .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                .limit(20L)
                .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                .offset(0L)
                .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                .total(4L)
                .addItem(
                    TrackObject.builder()
                        .id("id")
                        .album(
                            TrackObject.Album.builder()
                                .id("2up3OPMp9Tb4dAKM2erWXQ")
                                .albumType(TrackObject.Album.AlbumType.COMPILATION)
                                .addArtist(
                                    SimplifiedArtistObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder()
                                                .published(true)
                                                .spotify("spotify")
                                                .build()
                                        )
                                        .href("href")
                                        .name("name")
                                        .published(true)
                                        .type(SimplifiedArtistObject.Type.ARTIST)
                                        .uri("uri")
                                        .build()
                                )
                                .availableMarkets(listOf("CA", "BR", "IT"))
                                .externalUrls(
                                    ExternalUrlObject.builder()
                                        .published(true)
                                        .spotify("spotify")
                                        .build()
                                )
                                .href("href")
                                .addImage(
                                    ImageObject.builder()
                                        .height(300L)
                                        .url(
                                            "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                        )
                                        .width(300L)
                                        .published(true)
                                        .build()
                                )
                                .name("name")
                                .releaseDate("1981-12")
                                .releaseDatePrecision(TrackObject.Album.ReleaseDatePrecision.YEAR)
                                .totalTracks(9L)
                                .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                                .published(true)
                                .restrictions(
                                    AlbumRestrictionObject.builder()
                                        .published(true)
                                        .reason(AlbumRestrictionObject.Reason.MARKET)
                                        .build()
                                )
                                .build()
                        )
                        .addArtist(
                            SimplifiedArtistObject.builder()
                                .id("id")
                                .externalUrls(
                                    ExternalUrlObject.builder()
                                        .published(true)
                                        .spotify("spotify")
                                        .build()
                                )
                                .href("href")
                                .name("name")
                                .published(true)
                                .type(SimplifiedArtistObject.Type.ARTIST)
                                .uri("uri")
                                .build()
                        )
                        .addAvailableMarket("string")
                        .discNumber(0L)
                        .durationMs(0L)
                        .explicit(true)
                        .externalIds(
                            ExternalIdObject.builder()
                                .ean("ean")
                                .isrc("isrc")
                                .published(true)
                                .upc("upc")
                                .build()
                        )
                        .externalUrls(
                            ExternalUrlObject.builder().published(true).spotify("spotify").build()
                        )
                        .href("href")
                        .isLocal(true)
                        .isPlayable(true)
                        .linkedFrom(
                            LinkedTrackObject.builder()
                                .id("id")
                                .externalUrls(
                                    ExternalUrlObject.builder()
                                        .published(true)
                                        .spotify("spotify")
                                        .build()
                                )
                                .href("href")
                                .published(true)
                                .type("type")
                                .uri("uri")
                                .build()
                        )
                        .name("name")
                        .popularity(0L)
                        .previewUrl("preview_url")
                        .published(true)
                        .restrictions(
                            TrackRestrictionObject.builder()
                                .published(true)
                                .reason("reason")
                                .build()
                        )
                        .trackNumber(0L)
                        .type(TrackObject.Type.TRACK)
                        .uri("uri")
                        .build()
                )
                .published(true)
                .build()

        assertThat(topListTopTracksPageResponse.href())
            .isEqualTo("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
        assertThat(topListTopTracksPageResponse.limit()).isEqualTo(20L)
        assertThat(topListTopTracksPageResponse.next())
            .isEqualTo("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
        assertThat(topListTopTracksPageResponse.offset()).isEqualTo(0L)
        assertThat(topListTopTracksPageResponse.previous())
            .isEqualTo("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
        assertThat(topListTopTracksPageResponse.total()).isEqualTo(4L)
        assertThat(topListTopTracksPageResponse.items())
            .containsExactly(
                TrackObject.builder()
                    .id("id")
                    .album(
                        TrackObject.Album.builder()
                            .id("2up3OPMp9Tb4dAKM2erWXQ")
                            .albumType(TrackObject.Album.AlbumType.COMPILATION)
                            .addArtist(
                                SimplifiedArtistObject.builder()
                                    .id("id")
                                    .externalUrls(
                                        ExternalUrlObject.builder()
                                            .published(true)
                                            .spotify("spotify")
                                            .build()
                                    )
                                    .href("href")
                                    .name("name")
                                    .published(true)
                                    .type(SimplifiedArtistObject.Type.ARTIST)
                                    .uri("uri")
                                    .build()
                            )
                            .availableMarkets(listOf("CA", "BR", "IT"))
                            .externalUrls(
                                ExternalUrlObject.builder()
                                    .published(true)
                                    .spotify("spotify")
                                    .build()
                            )
                            .href("href")
                            .addImage(
                                ImageObject.builder()
                                    .height(300L)
                                    .url(
                                        "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                    )
                                    .width(300L)
                                    .published(true)
                                    .build()
                            )
                            .name("name")
                            .releaseDate("1981-12")
                            .releaseDatePrecision(TrackObject.Album.ReleaseDatePrecision.YEAR)
                            .totalTracks(9L)
                            .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                            .published(true)
                            .restrictions(
                                AlbumRestrictionObject.builder()
                                    .published(true)
                                    .reason(AlbumRestrictionObject.Reason.MARKET)
                                    .build()
                            )
                            .build()
                    )
                    .addArtist(
                        SimplifiedArtistObject.builder()
                            .id("id")
                            .externalUrls(
                                ExternalUrlObject.builder()
                                    .published(true)
                                    .spotify("spotify")
                                    .build()
                            )
                            .href("href")
                            .name("name")
                            .published(true)
                            .type(SimplifiedArtistObject.Type.ARTIST)
                            .uri("uri")
                            .build()
                    )
                    .addAvailableMarket("string")
                    .discNumber(0L)
                    .durationMs(0L)
                    .explicit(true)
                    .externalIds(
                        ExternalIdObject.builder()
                            .ean("ean")
                            .isrc("isrc")
                            .published(true)
                            .upc("upc")
                            .build()
                    )
                    .externalUrls(
                        ExternalUrlObject.builder().published(true).spotify("spotify").build()
                    )
                    .href("href")
                    .isLocal(true)
                    .isPlayable(true)
                    .linkedFrom(
                        LinkedTrackObject.builder()
                            .id("id")
                            .externalUrls(
                                ExternalUrlObject.builder()
                                    .published(true)
                                    .spotify("spotify")
                                    .build()
                            )
                            .href("href")
                            .published(true)
                            .type("type")
                            .uri("uri")
                            .build()
                    )
                    .name("name")
                    .popularity(0L)
                    .previewUrl("preview_url")
                    .published(true)
                    .restrictions(
                        TrackRestrictionObject.builder().published(true).reason("reason").build()
                    )
                    .trackNumber(0L)
                    .type(TrackObject.Type.TRACK)
                    .uri("uri")
                    .build()
            )
        assertThat(topListTopTracksPageResponse.published()).isEqualTo(true)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val topListTopTracksPageResponse =
            TopListTopTracksPageResponse.builder()
                .href("https://api.spotify.com/v1/me/shows?offset=0&limit=20\n")
                .limit(20L)
                .next("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                .offset(0L)
                .previous("https://api.spotify.com/v1/me/shows?offset=1&limit=1")
                .total(4L)
                .addItem(
                    TrackObject.builder()
                        .id("id")
                        .album(
                            TrackObject.Album.builder()
                                .id("2up3OPMp9Tb4dAKM2erWXQ")
                                .albumType(TrackObject.Album.AlbumType.COMPILATION)
                                .addArtist(
                                    SimplifiedArtistObject.builder()
                                        .id("id")
                                        .externalUrls(
                                            ExternalUrlObject.builder()
                                                .published(true)
                                                .spotify("spotify")
                                                .build()
                                        )
                                        .href("href")
                                        .name("name")
                                        .published(true)
                                        .type(SimplifiedArtistObject.Type.ARTIST)
                                        .uri("uri")
                                        .build()
                                )
                                .availableMarkets(listOf("CA", "BR", "IT"))
                                .externalUrls(
                                    ExternalUrlObject.builder()
                                        .published(true)
                                        .spotify("spotify")
                                        .build()
                                )
                                .href("href")
                                .addImage(
                                    ImageObject.builder()
                                        .height(300L)
                                        .url(
                                            "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
                                        )
                                        .width(300L)
                                        .published(true)
                                        .build()
                                )
                                .name("name")
                                .releaseDate("1981-12")
                                .releaseDatePrecision(TrackObject.Album.ReleaseDatePrecision.YEAR)
                                .totalTracks(9L)
                                .uri("spotify:album:2up3OPMp9Tb4dAKM2erWXQ")
                                .published(true)
                                .restrictions(
                                    AlbumRestrictionObject.builder()
                                        .published(true)
                                        .reason(AlbumRestrictionObject.Reason.MARKET)
                                        .build()
                                )
                                .build()
                        )
                        .addArtist(
                            SimplifiedArtistObject.builder()
                                .id("id")
                                .externalUrls(
                                    ExternalUrlObject.builder()
                                        .published(true)
                                        .spotify("spotify")
                                        .build()
                                )
                                .href("href")
                                .name("name")
                                .published(true)
                                .type(SimplifiedArtistObject.Type.ARTIST)
                                .uri("uri")
                                .build()
                        )
                        .addAvailableMarket("string")
                        .discNumber(0L)
                        .durationMs(0L)
                        .explicit(true)
                        .externalIds(
                            ExternalIdObject.builder()
                                .ean("ean")
                                .isrc("isrc")
                                .published(true)
                                .upc("upc")
                                .build()
                        )
                        .externalUrls(
                            ExternalUrlObject.builder().published(true).spotify("spotify").build()
                        )
                        .href("href")
                        .isLocal(true)
                        .isPlayable(true)
                        .linkedFrom(
                            LinkedTrackObject.builder()
                                .id("id")
                                .externalUrls(
                                    ExternalUrlObject.builder()
                                        .published(true)
                                        .spotify("spotify")
                                        .build()
                                )
                                .href("href")
                                .published(true)
                                .type("type")
                                .uri("uri")
                                .build()
                        )
                        .name("name")
                        .popularity(0L)
                        .previewUrl("preview_url")
                        .published(true)
                        .restrictions(
                            TrackRestrictionObject.builder()
                                .published(true)
                                .reason("reason")
                                .build()
                        )
                        .trackNumber(0L)
                        .type(TrackObject.Type.TRACK)
                        .uri("uri")
                        .build()
                )
                .published(true)
                .build()

        val roundtrippedTopListTopTracksPageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(topListTopTracksPageResponse),
                jacksonTypeRef<TopListTopTracksPageResponse>(),
            )

        assertThat(roundtrippedTopListTopTracksPageResponse).isEqualTo(topListTopTracksPageResponse)
    }
}
